### ISSUE TITLE
strange error displayed in sublimetext console.

### ISSUE THREAD

**Issue by canfoderiskii** [niosus/EasyClangComplete#190]
I don't know how to reproduce the error but I often see it. This kind of error usually occurs many times.
Here is the error message sample:
>[2017-01-06 21:56:27,400 - ERROR    - concurrent.futures] exception calling callback for <Future at 0x1e2e9a74f28 state=finished raised KeyError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 209, in config_removed
    log.debug(" removed config for id: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 363, in clear_for_view
    del self._cache[v_id]
KeyError: 96

The value after the word `KeyError` varies from different error messages.

**Comment by canfoderiskii** [comment]
Also sometimes the sublime text plugin host dies, I have to restart the editor.
Here is the exception message from console:
>Traceback (most recent call last):
  File "D:\GreenProg\SublimeText\sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 137, in on_activated_async
    self.view_config_manager.load_for_view(view, settings)
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 341, in load_for_view
    res = self._cache[v_id].update_if_needed(view, settings)
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 91, in update_if_needed
    self.completer.update(view, settings.errors_on_save)
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\lib_complete.py", line 217, in update
    self.show_errors(view, self.tu.diagnostics)
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\base_complete.py", line 82, in show_errors
    errors = self.compiler_variant.errors_from_output(output)
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\compiler_variant.py", line 102, in errors_from_output
    for diag in output:
  File "C:\Users\Geminii\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\clang\cindex39.py", line 2808, in __getitem__
    diag = conf.lib.clang_getDiagnostic(self.tu, key)
OSError: exception: access violation reading 0x0000000000000768
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

**Comment by niosus** [comment]
Yeah, I've seen this before. I don't know the reason just yet. Thanks for reporting. I will look into it around next week.

**Comment by niosus** [comment]
The reason was that the view became invalid in the process of opening or closing. This way, there was no key in the dictionary to remove or to fetch. I am protecting the code against that from now on.
