### ISSUE TITLE
llvm/clang issue on windows 10

### ISSUE THREAD

**Issue by mihnen** [niosus/EasyClangComplete#197]
Here is what happened when I try to run this extension on windows 10 64 bit. Have tried multiple versions of llvm/clang both 32bit and 64bit. The error doesn't occur when not trying to usb libclang but completion doesn't work either in that mode.

```
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
DEBUG:EasyClangComplete.plugin.completion.lib_complete: using bundled cindex: EasyClangComplete.clang.cindex36
DEBUG:EasyClangComplete.clang.utils: platform: ('64bit', 'WindowsPE')
DEBUG:EasyClangComplete.clang.utils: python version: 3.3.6
DEBUG:EasyClangComplete.clang.utils: we are on 'Windows'
DEBUG:EasyClangComplete.clang.utils: searching for: 'libclang.dll'
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 55, in plugin_loaded
    handle_plugin_loaded_function()
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 113, in on_plugin_loaded
    self.on_activated_async(sublime.active_window().active_view())
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 137, in on_activated_async
    self.view_config_manager.load_for_view(view, settings)
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 345, in load_for_view
    config = ViewConfig(view, settings)
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 58, in __init__
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 163, in __generate_essentials
    completer = ViewConfig.__init_completer(settings)
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\view_config.py", line 255, in __init_completer
    settings.clang_version)
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\completion\lib_complete.py", line 98, in __init__
    libclang_dir = ClangUtils.find_libclang_dir(clang_binary)
  File "C:\Users\Matthew\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\clang\utils.py", line 107, in find_libclang_dir
    startupinfo=startupinfo).decode('utf8').strip()
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
PermissionError: [WinError 5] Access is denied
```

**Comment by niosus** [comment]
Strange. It works on my windows 10. How exactly do you install clang?

**Comment by niosus** [comment]
@mihnen do you still experience this?

**Comment by mihnen** [comment]
Yes still an issue, I can't use this plugin because of it. I simply installed clang from the installer on the llvm website.

**Comment by niosus** [comment]
Please make sure you have the latest 64 bit clang 3.9. If the plugin still fails, please try to clone the other test repo, that I created for this purpose: https://github.com/niosus/test-complete-plugin

**Comment by simia** [comment]
Do you have clang binary set correctly in EasyClangComplete and is it in your PATH system env? Maybe that's the problem?

**Comment by mihnen** [comment]
Alright so it looks like when you install llvm you need to tell it to add it to the current users path. I had previously installed it without adding it to the path environment variable and instead configured clang_binary variable in the settings to use the full path to the binary.

**Comment by niosus** [comment]
Ok, great that you have solved it! I need to remember to add it to documentation at some point.
