### ISSUE TITLE
OSX_CLANG_VERSION contains no key for my apple-clang version

### ISSUE THREAD

**Issue by johnofcamas** [niosus/EasyClangComplete#216]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 480, in on_post_save_async
    callback.on_post_save_async(v)
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 194, in on_post_save_async
    settings = self.settings_manager.settings_for_view(view)
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 51, in settings_for_view
    self.__init_for_view(view)
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 97, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 94, in update_from_view
    self.__update_widcard_values(view)
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 239, in __update_widcard_values
    Tools.get_clang_version_str(self.clang_binary)
  File "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/tools.py", line 647, in get_clang_version_str
    version_str = OSX_CLANG_VERSION_DICT[osx_version]
KeyError: '8.1'
```

**Comment by niosus** [comment]
I have to find out to which python bindings does apple-clang 8.1 match and add it to the supported versions.

**Comment by niosus** [comment]
Following this: https://gist.github.com/yamaya/2924292

I see that the version should be the same as before. I will update the list in the plugin soon.

**Comment by niosus** [comment]
I will release this during this week

**Comment by johnofcamas** [comment]
Fantastic, thanks for such a quick response!
