### ISSUE TITLE
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f6e00189b90 state=finished raised KeyError>

### ISSUE THREAD

**Issue by dubnde** [niosus/EasyClangComplete#232]
First time installation seeing the following. Not exactly sure what it means but would appreciate some help. I cannot get completions to work as a result.

```
DEBUG:EasyClangComplete.plugin.tools: found 'compile_commands.json' file: /usr/jdoe/builds/projectx/compile_commands.json
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[current]: '/usr/jdoe/builds/projectx/compile_commands.json'
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[load new]
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f6e00189b90 state=finished raised KeyError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 260, in config_updated
    log.debug(" updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 349, in load_for_view
    config = ViewConfig(view, settings)
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 58, in __init__
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 174, in __generate_essentials
    flags += ViewConfig.__load_source_flags(view, settings, prefixes)
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 219, in __load_source_flags
    flags = flag_source.get_flags(view.file_name(), search_scope)
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/plugin/flags_sources/compilation_db.py", line 88, in get_flags
    db = self._parse_database(File(current_db_path))
  File "/usr/jdoe/.config/sublime-text-3/Packages/EasyClangComplete/plugin/flags_sources/compilation_db.py", line 125, in _parse_database
    command_as_list = CompilationDb.line_as_list(entry['command'])
KeyError: 'command'
DEBUG:EasyClangComplete.plugin.utils.thread_pool: Jobs still running: 0
DEBUG:EasyClangComplete.plugin.utils.thread_pool: Stopping progress animation.
DEBUG:EasyClangComplete.plugin.tools: file has unsupported syntax: `JSON`
DEBUG:EasyClangComplete.plugin.tools: file has unsupported syntax: `JSON`
```

**Comment by niosus** [comment]
Hello @dubnde sorry for that. Have you tried to restart Sublime Text? We still have some settings not really working without the restart.

**Comment by dubnde** [comment]
oh yeah. That was it. Restarts works. Thanks very much for the rapid response

**Comment by niosus** [comment]
No problem. I am planning to iron these things out, but it's less fun to do it than new features and it's harder to force myself to do it after a work day :) Hope you like the plugin!

**Comment by dubnde** [comment]
Yes. So far so good with using an existing `compile_commands.json` . So code completion done for C/C++ done ✔️. Next I need code navigation - something like https://github.com/Andersbakken/rtags if I can get a pluggin as easy as this one to setup :crossed_fingers: .

**Comment by niosus** [comment]
We don't have code navigation yet, but if you hover a variable with your mouse, you should be able to see its signature with the links to the locations of the definitions.

**Comment by dubnde** [comment]
Yes I did fortuitously see the links to the locations of the definitions

**Comment by niosus** [comment]
I hope that at some point we will have the navigate to definition functionality in place. I don't use it that much as I am quite happy with sublime's own <kbd>F12</kbd> to navigate to definition and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> to find a variable in the project. But it seems fitting to have them as part of the plugin.

**Comment by dubnde** [comment]
`F12 `does find the definition. Something like `rtags ` actually parses and understands the language. Also uses same `compile_commands.json` input db file.
