### ISSUE TITLE
Running compiled from source clang; Version '3.8' of apple-clang is not supported yet 

### ISSUE THREAD

**Issue by silver008** [niosus/EasyClangComplete#248]
Hi, I'm running on OSX on my own compiled-from-source version of clang 3.8.1, and tools.py's `OSX_CLANG_VERSION_DICT` is assuming an apple-packaged clang, it seems. `OSX_CLANG_VERSION_DICT` is a dictionary that maps apple's clang version numbers to the actual clang version. However, my version is already the standard clang version (3.8.1). I hacked this by just adding '3.8': '3.8' as an entry in the dictionary, and that solves my problem. But, I'd prefer to have this solved properly for the broader community (and not have my change get clobbered upon an update).

Or... is there some configuration I should be doing to fix this some other way?

Thank you. Debug output below.

```
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 88
DEBUG:EasyClangComplete.plugin.settings.settings_manager: no settings for view 88. Reinitializing.
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Overriding settings by project ones if needed:
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Valid prefixes: ['ecc_', 'easy_clang_complete_']
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
error: EasyClangComplete
                    Version '3.8' of apple-clang is not supported yet.
                    Please open an issue for it.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 150, in on_activated_async
    settings = self.settings_manager.settings_for_view(view)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 51, in settings_for_view
    self.__init_for_view(view)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 97, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 104, in update_from_view
    self.__update_widcard_values(view)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 252, in __update_widcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/tools.py", line 696, in get_clang_version_str
    raise e
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/tools.py", line 689, in get_clang_version_str
    version_str = OSX_CLANG_VERSION_DICT[osx_version]
KeyError: '3.8'
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 88
DEBUG:EasyClangComplete.plugin.utils.thread_pool:submitting job: job: 'update', args: ([<sublime.View object at 0x10cc3cb50>, <EasyClangComplete.plugin.settings.settings_storage.SettingsStorage object at 0x10c8b3d90>])
DEBUG:EasyClangComplete.plugin.utils.thread_pool: running 1 jobs
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.view_config: generate new config for path: 88
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
ERROR:concurrent.futures:exception calling callback for <Future at 0x10cc3c6d0 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/view_config.py", line 349, in load_for_view
    config = ViewConfig(view, settings)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/view_config.py", line 58, in __init__
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/view_config.py", line 166, in __generate_essentials
    completer = ViewConfig.__init_completer(settings)
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/view_config.py", line 258, in __init_completer
    settings.clang_version,
AttributeError: 'SettingsStorage' object has no attribute 'clang_version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 248, in config_updated
    log.debug(" updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/Users/silver/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/view_config.py", line 364, in load_for_view
    e.msg)
AttributeError: 'AttributeError' object has no attribute 'msg'
DEBUG:EasyClangComplete.plugin.utils.thread_pool: Jobs still running: 0
DEBUG:EasyClangComplete.plugin.utils.thread_pool: Stopping progress animation.
Package Control: No updated packages
```

**Comment by niosus** [comment]
Hey, thanks a lot for opening the issue! I was hesitant to add it before because apple is really good at changing the underlying llvm clang version which may lead to wrong bindings. If you say that just adding 3.8 to the dictionary solves this for you, I am happy to add it. Will add soon.

**Comment by niosus** [comment]
I will try to release this today.
