### ISSUE TITLE
Python errors on any click or key press

### ISSUE THREAD

**Issue by pl-ca** [niosus/EasyClangComplete#26]
Hi @niosus , I have installed the plug-in from package control and after configuring my includes I get the following errors on the console, which seems to come from the fact that `completer` is not initialized. I set verbose `true` but it seems to fail before it has the change to print anything. These errors happen as soon as I click anywhere or type anything. Any idea?

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "/home/plca/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 88, in on_activated_async
    if completer.exists_for_view(view.id()):
AttributeError: 'NoneType' object has no attribute 'exists_for_view'
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "/home/plca/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 88, in on_activated_async
    if completer.exists_for_view(view.id()):
AttributeError: 'NoneType' object has no attribute 'exists_for_view'
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/opt/sublime_text_3/sublime_plugin.py", line 314, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "/home/plca/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 111, in on_selection_modified
    completer.error_vis.show_popup_if_needed(view, row)
AttributeError: 'NoneType' object has no attribute 'error_vis'
```

**Comment by niosus** [comment]
Hey @pl-ca 

This is something new. There has to be some part of log (somewhere after all plugins have been initialized by sublime text) that initializes the plugin. Can you  close and reopen sublime text and try to search for it?

**Comment by pl-ca** [comment]
Actually, when I attempted to get this error again, it worked fine. Not sure what happened but I guess we can close this issue :)

**Comment by niosus** [comment]
Hm. Strange. Feel free to reopen if you encounter it again.
