### ISSUE TITLE
Errors After Clean Install [fixed by sublime text restart]

### ISSUE THREAD

**Issue by dude719** [niosus/EasyClangComplete#275]
Right after a clean installation I get errors in the console window.

```
ignored packages updated to: ["EasyClangComplete", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin EasyClangComplete.EasyClangComplete
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 52, in plugin_loaded
    handle_plugin_loaded_function()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 109, in on_plugin_loaded
    self.settings_manager = SettingsManager()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 37, in __init__
    self.__init_default_settings()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 128, in __init_default_settings
    valid, error_msg = self.__default_settings.is_valid()
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 139, in is_valid
    if self.progress_style not in SettingsStorage.PROGRESS_STYLES:
AttributeError: 'SettingsStorage' object has no attribute 'progress_style'
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ERROR:EasyClangComplete.plugin.tools: view file_name is None
reloading settings Packages/User/Preferences.sublime-settings
ERROR:EasyClangComplete.plugin.tools: view file_name is None
DEBUG:EasyClangComplete.plugin.tools: file has unsupported syntax: `JSON`
ERROR:EasyClangComplete.plugin.tools: view has wrong syntax: JSON
DEBUG:EasyClangComplete.EasyClangComplete: cannot clear status, 'NoneType' object has no attribute 'erase_status'
DEBUG:EasyClangComplete.plugin.tools: file has unsupported syntax: `JSON`
ERROR:EasyClangComplete.plugin.tools: view has wrong syntax: JSON
DEBUG:EasyClangComplete.plugin.tools: file has unsupported syntax: `JSON`
ERROR:EasyClangComplete.plugin.tools: view has wrong syntax: JSON
ERROR:EasyClangComplete.plugin.tools: view file_name is None
DEBUG:EasyClangComplete.EasyClangComplete: cannot clear status, 'NoneType' object has no attribute 'erase_status'
ERROR:EasyClangComplete.plugin.tools: view file_name is None
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 167, in on_selection_modified
    settings = self.settings_manager.settings_for_view(view)
AttributeError: 'EasyClangComplete' object has no attribute 'settings_manager'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 167, in on_selection_modified
    settings = self.settings_manager.settings_for_view(view)
AttributeError: 'EasyClangComplete' object has no attribute 'settings_manager'
ERROR:EasyClangComplete.plugin.tools: view file_name is None
ERROR:EasyClangComplete.plugin.tools: view file_name is None
ERROR:EasyClangComplete.plugin.tools: view file_name is None
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 167, in on_selection_modified
    settings = self.settings_manager.settings_for_view(view)
AttributeError: 'EasyClangComplete' object has no attribute 'settings_manager'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "C:\Users\Owner\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 167, in on_selection_modified
    settings = self.settings_manager.settings_for_view(view)
...
```

**Comment by dude719** [comment]
Everything is all good after a restart, thanks!

**Comment by niosus** [comment]
Yeah, sorry for inconvenience. I will get to it, I promise :) Won't promise exactly when, though. :)
