### ISSUE TITLE
Problem reloading plugin after initial plugin install

### ISSUE THREAD

**Issue by static7s** [niosus/EasyClangComplete#276]
Let me preface this by saying that I've never done anything with Sublime plugins before, so it may be that I managed to screw something up somehow. 
This is the console output from restarting Sublime after installing the plugin:

```
startup, version: 3103 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/Minion
packages path: /home/Minion/.config/sublime-text-3/Packages
state path: /home/Minion/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/Minion/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.067737
startup time: 0.196181
first paint time: 0.203066
scan: /ados/ados_core/internal_signal_processing has been seen before, skipping (using inode) previous 
path: /ados/ados_core/internal+signal_processing inode: 4458136
scan: /ados/ados_core/external_signal_processing has been seen before, skipping (using inode) previous 
path: /ados/ados_core/external_signal_processing inode: 6162435
scan: /ados/ados_core/wifi has been seen before, skipping (using inode) previous path: /ados/ados_core/wifi inode: 7738577
scan: /ados/util/persistent_storage/util_gcc_linux_4_7_3 has been seen before, skipping (using inode) 
previous path: /ados/util/util_gcc_linux_4_7_3 inode: 7479569
scan: /ados/util/util_mingw_linux_win32_3_4_5/local has been seen before, skipping (using inode) 
previous path: /ados/util/util_mingw_linux_win32_3_4_5 inode: 7602568
scan: /ados/util/util_mingw_linux_win32_3_4_5/usr has been seen before, skipping (using inode) previous 
path: /ados/util/util_mingw_linux_win32_3_4_5 inode: 7602568
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin EasyClangComplete.EasyClangComplete
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/Minion/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 19, in <module>
    from .plugin.utils import thread_pool
  File "/home/Minion/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/thread_pool.py", line 8, in <module>
    from concurrent import futures
  File "./concurrent/futures/__init__.py", line 17, in <module>
  File "./concurrent/futures/process.py", line 52, in <module>
  File "./multiprocessing/__init__.py", line 58, in <module>
ImportError: No module named '_multiprocessing'
reloading plugin Terminal.Terminal
reloading plugin ssl-linux.loader
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
plugins loaded
Package Control: No updated packages
```
I then discovered that the Settings menu item for the plugin is grayed out:
![image](https://user-images.githubusercontent.com/7786502/26893128-702cdfc6-4b88-11e7-93d8-6c6859828b35.png)

If I could turn on the verbose setting and provide a log with it, I would...

**Comment by simia** [comment]
You might start with installing newer version of Sublime 3103 is more than year old. 
https://www.sublimetext.com/3

**Comment by niosus** [comment]
I agree with @simia 
But I guess we should still investigate if we should bump up the minimal version of sublime text that we require.

**Comment by static7s** [comment]
Thanks, that did the trick! I wasn't even aware that I had an outdated version of Sublime.

**Comment by niosus** [comment]
Ok, will close this one then.
