### ISSUE TITLE
.no-sublime-package: is this really necessary?

### ISSUE THREAD

**Issue by rwols** [niosus/EasyClangComplete#303]
.no-sublime-package causes the package to be downloaded unpacked in the Packages folder by Package Control. Since the whole codebase is all Python and there are no binaries anywhere, it seems like this is unnecessary, but I'm probably missing something important. Why is there a .no-sublime-package?

**Comment by niosus** [comment]
There historically were two reasons for this.
1. It was not working as expected with `.no-sublime-package` :laughing: And at that point in time I was focused on making the functionality available and not so much about the speed.
2. I want people to participate and to dig into the code in case smth goes south. This is much easier to do when the package is unpacked. 

Maybe, I could try adding that, but I would probably leave it as it is if there is not a huge concern from the people. I am open to discussing this decision.

**Comment by niosus** [comment]
Update on this one. Trying it with a sublime package instead of source code gives this error:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "EasyClangComplete in /home/igor/.config/sublime-text-3/Installed Packages/EasyClangComplete.sublime-package", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugin.view_config in /home/igor/.config/sublime-text-3/Installed Packages/EasyClangComplete.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugin.error_vis.phantom_error_vis in /home/igor/.config/sublime-text-3/Installed Packages/EasyClangComplete.sublime-package", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugin.error_vis.popup_error_vis in /home/igor/.config/sublime-text-3/Installed Packages/EasyClangComplete.sublime-package", line 21, in <module>
  File "plugin.error_vis.popup_error_vis in /home/igor/.config/sublime-text-3/Installed Packages/EasyClangComplete.sublime-package", line 31, in PopupErrorVis
NotADirectoryError: [Errno 20] Not a directory: '/home/igor/.config/sublime-text-3/Installed Packages/EasyClangComplete.sublime-package/plugin/html/error_popup.html'
```

Unfortunately, I don't have the time to solve this one. I am still not fully convinced I want to move towards a packaged release. In case somebody feels that his bandwidth is too narrow to allow for updating from source code, I might consider a pull request for this. Anyway, I still feel that it is more important to let people dig through the code easily compared to saving some kilobytes of data on update.

I will close this issue for now.
