### ISSUE TITLE
Cannot find libclang in /usr/lib/

### ISSUE THREAD

**Issue by kgizdov** [niosus/EasyClangComplete#308]
# Please do this before submitting: #
- [x] check for already solved issues
- [x] try restarting Sublime Text

# Please state the following: #
- Sublime Text version: `3.3126`
- which system are you on: `ArchLinux x64`

This is possibly related to #214 
So for some reason I have to manually set the libclang path to `/usr/lib/libclang.so` or I get the error below and the following error about not having set `use_libclang` to `true`. I do have it set to `true`, but I think the extension just can't find it the path. As far as I know, this is the standard path to libclang on all distros and it links to the actual installed version. Not sure why this is a problem.

```
[ECC:INFO   ]: init completer based on clang from cmd
error: 
        EasyClangComplete:
        "use_libclang" is false
        "show_type_info" is true.

        Unfortunately, there is no way to show type info
        if you are not using libclang.

        Please use libclang or set "show_type_info" to false.
        
ERROR:concurrent.futures:exception calling callback for <Future at 0x7fac5df3ecd0 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/gizdov/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 329, in info_finished
    (tooltip_request, result) = future.result()
TypeError: 'NoneType' object is not iterable
```

**Comment by niosus** [comment]
@kgizdov sounds strange indeed. From the looks of it it should be working. Can you enable `verbose` setting and attach the full log from the console since you start sublime text till you see the above mentioned error.

**Comment by kgizdov** [comment]
@niosus so removing the exact path for `libclang` and putting `"verbose": true` now produces only this:
```
[ECC:WARNING]:  clang could not find 'libclang-4.0.so'
[ECC:INFO   ]: found libclang library file: '/usr/lib64/libclang.so'
```
This is after getting info from `clang++ -v`.
Two things concern me. Firstly, that `lib64` does not exist on ArchLinux. It's only a symlink to `lib`. So maybe the error I got was intermittent based on filesystem error, or mishandling of x64 specific search path like that.
Second, why is it looking for `libclang-4.0.so`, when it should be looking for `libclang.so.4` or `libclang.so.4.0`?
This error is probably a very rare edge case, dependent on the search algo that you use, that sometimes fails to resolve `libclang` based on similar things to what I pointed out. What do you think?

**Comment by kgizdov** [comment]
Here's also the full log:
```
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[MainThread]: on_activated_async view id 68
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 68. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[MainThread]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I$project_base_path/include' to '-I/home/gizdov/Git/BsJpsiPhi/include'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I$project_base_path/src' to '-I/home/gizdov/Git/BsJpsiPhi/src'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/4.0.1/include'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[MainThread]: settings initialized for view: 68
[ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-6]: submitting job: job: 'update', args: ([<sublime.View object at 0x7fd60c0951d0>, <EasyClangComplete.plugin.settings.settings_storage.SettingsStorage object at 0x7fd60c095250>])
[ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-6]: running 1 jobs
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-12]: generate new config for path: 68
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-12]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-12]: using bundled cindex: EasyClangComplete.plugin.clang.cindex40
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: platform: ('64bit', '')
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: python version: 3.3.6
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: we are on 'Linux'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: user provided libclang_path: <some_path_here>
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: searching for: 'libclang-$version.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: libclang search output = 'libclang-4.0.so'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-12]: real output: libclang-4.0.so
[ECC:WARNING]:[utils.py]:[find_libclang_dir]:[Thread-12]:  clang could not find 'libclang-4.0.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: searching for: 'libclang.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-12]: libclang search output = '/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib64/libclang.so'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-12]: real output: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib64/libclang.so
[ECC:INFO]:[utils.py]:[find_libclang_dir]:[Thread-12]: found libclang library file: '/usr/lib64/libclang.so'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-12]: [cmake]:[get]: for file /home/gizdov/Git/BsJpsiPhi/analysis/src/ApplySelection_bd.cpp
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-12]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: searching 'CMakeLists.txt' from '/home/gizdov/Git/BsJpsiPhi/analysis/src' to '/home/gizdov/Git/BsJpsiPhi'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-12]: [cmake]:[current]: 'None'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-12]: [cmake]:[generate new db]
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-12]: [db]:[get]: for file /home/gizdov/Git/BsJpsiPhi/analysis/src/ApplySelection_bd
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-12]: [db]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: searching 'compile_commands.json' from '/home/gizdov/Git/BsJpsiPhi/analysis/src' to '/home/gizdov/Git/BsJpsiPhi'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-12]: [db]:[current]: 'None'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-12]: [db]:[load new]
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-12]: [db]:[no new]: return None
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-12]: [clang_complete_file]:[get]: for file /home/gizdov/Git/BsJpsiPhi/analysis/src/ApplySelection_bd.cpp
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-12]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-12]: searching '.clang_complete' from '/home/gizdov/Git/BsJpsiPhi/analysis/src' to '/home/gizdov/Git/BsJpsiPhi'
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-12]: [clang_complete_file]:[current]: 'None'
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-13]: view file_name is None
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-12]: view is 68
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-12]: translation unit does not exist. Creating.
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-12]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', '-I/usr/include', '-I/usr/include/root', '-I/opt/cuda/include', '-I/home/gizdov/Git/BsJpsiPhi/include', '-I/home/gizdov/Git/BsJpsiPhi/src', '-I/usr/lib/clang/4.0.1/include', '-I/home/gizdov/Git/BsJpsiPhi/analysis/src', '-I/home/gizdov/Git/BsJpsiPhi/analysis']
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-12]: compilation started for view id: 68
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-12]: compilation done in 0.5567803382873535 seconds
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-12]: reparsing translation_unit for view 68
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-12]: reparsed in 0.7864444255828857 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-12]: generating error regions for view 68
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-12]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-12]: showing error regions: []
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-12]: starting timer to remove old configs.
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-12]: [timer]: start for view: 68
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-12]: [timer]: active for views: dict_keys([68])
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-12]: updated config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7fd5fcc64ed0>
[ECC:DEBUG]:[thread_pool.py]:[__stop_progress_animation]:[Thread-12]: Jobs still running: 0
[ECC:DEBUG]:[thread_pool.py]:[__stop_progress_animation]:[Thread-12]: Stopping progress animation.
[ECC:DEBUG]:[view_config.py]:[__cancel_timer]:[Thread-17]: [timer]: stop for view: 68
[ECC:DEBUG]:[view_config.py]:[__cancel_timer]:[Thread-17]: [timer]: active for views: dict_keys([])
[ECC:DEBUG]:[view_config.py]:[__remove_old_config]:[Thread-17]: [skip] young config: Age 61.533252000808716 < 1800. View: 68.
[ECC:DEBUG]:[view_config.py]:[__remove_old_config]:[Thread-17]: [timer]: restart.
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-17]: [timer]: start for view: 68
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-17]: [timer]: active for views: dict_keys([68])
[ECC:DEBUG]:[view_config.py]:[__cancel_timer]:[Thread-20]: [timer]: stop for view: 68
[ECC:DEBUG]:[view_config.py]:[__cancel_timer]:[Thread-20]: [timer]: active for views: dict_keys([])
[ECC:DEBUG]:[view_config.py]:[__remove_old_config]:[Thread-20]: [skip] young config: Age 121.53417229652405 < 1800. View: 68.
[ECC:DEBUG]:[view_config.py]:[__remove_old_config]:[Thread-20]: [timer]: restart.
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-20]: [timer]: start for view: 68
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-20]: [timer]: active for views: dict_keys([68])
```

**Comment by niosus** [comment]
Hmmm. So the log suggests that everything is working as expected:
```
found libclang library file: '/usr/lib64/libclang.so'
```
And then actually parsing the translation unit: 
```
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-12]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', '-I/usr/include', '-I/usr/include/root', '-I/opt/cuda/include', '-I/home/gizdov/Git/BsJpsiPhi/include', '-I/home/gizdov/Git/BsJpsiPhi/src', '-I/usr/lib/clang/4.0.1/include', '-I/home/gizdov/Git/BsJpsiPhi/analysis/src', '-I/home/gizdov/Git/BsJpsiPhi/analysis']
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-12]: compilation started for view id: 68
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-12]: compilation done in 0.5567803382873535 seconds
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-12]: reparsing translation_unit for view 68
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-12]: reparsed in 0.7864444255828857 seconds
```

I feel that the original issue is somehow related to the symlink resolving. 

As for your question about where the version should go, there are systems, where binaries are named in this way and don't have a `libclang.so`.

**Comment by kgizdov** [comment]
Just had another error. I did not have the verbose enabled as I turned it off this morning after the tests. The strange thing is - Sublime was running for 3-4 hours before the error occurred. So the plugin crashed at runtime, way after initial path resolution. Not sure if that helps.

**Comment by niosus** [comment]
@kgizdov please leave the debug output on and submit the log in case you see the error again. Currently, I don't have any good idea on what causes it. Also, seems that my earlies suggestion helped. Maybe the new error is even unrelated. I will close this one for now. In case I misunderstood something or it still occurs, feel free to reopen this issue.

**Comment by kgizdov** [comment]
[ECC_bug_report.zip](https://github.com/niosus/EasyClangComplete/files/1273398/ECC_bug_report.zip)
@niosus unfortunately, none of your suggestions helped. I keep getting the same error over and over again constantly. I now think it is not connected to finding libclang, but to the way the output from it is parsed. Please have a look at the attached log and in particular to the following lines:
```
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[MainThread]: config exists for path: 193
[ECC:DEBUG]:[popup_error_vis.py]:[show_popup_if_needed]:[MainThread]: no error regions for row: 164
[ECC:DEBUG]:[view_config.py]:[__cancel_timer]:[Thread-1637]: [timer]: stop for view: 190
[ECC:DEBUG]:[view_config.py]:[__cancel_timer]:[Thread-1637]: [timer]: active for views: dict_keys([193, 196, 187])
[ECC:DEBUG]:[view_config.py]:[__remove_old_config]:[Thread-1637]: [skip] young config: Age 616.40181183815 < 1800. View: 190.
[ECC:DEBUG]:[view_config.py]:[__remove_old_config]:[Thread-1637]: [timer]: restart.
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-1637]: [timer]: start for view: 190
[ECC:DEBUG]:[view_config.py]:[__start_timer]:[Thread-1637]: [timer]: active for views: dict_keys([193, 196, 187, 190])
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 458, in <lambda>
    run_callback('on_pre_save', callback, lambda: callback.on_pre_save(v))
  File "trailing_spaces in /home/gizdov/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 424, in on_pre_save
  File "trailing_spaces in /home/gizdov/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./python3.3/codecs.py", line 896, in open
FileNotFoundError: [Errno 2] No such file or directory: '/home/gizdov/Git/pdqa-automation/gain/gain.cpp'
[ECC:DEBUG]:[EasyClangComplete.py]:[on_post_save_async]:[Dummy-13]: saving view: 208
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-13]: on_activated_async view id 208
[ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-1671]: submitting job: job: 'update', args: ([<sublime.View object at 0x7f8c954dcd90>, <EasyClangComplete.plugin.settings.settings_storage.SettingsStorage object at 0x7f8c95917610>])
[ECC:DEBUG]:[thread_pool.py]:[__submit_jobs]:[Thread-1671]: running 1 jobs
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-94]: generate new config for path: 208
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-94]: init completer based on libclang
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-94]:  No cindex module for clang version: 
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-94]: cannot initialize completer with libclang.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-94]: falling back to using clang in a subprocess.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-94]: init completer based on clang from cmd
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-94]: [cmake]:[get]: for file /home/gizdov/Git/pdqa-automation/gain/gain.cpp
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-94]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-94]: searching 'CMakeLists.txt' from '/home/gizdov/Git/pdqa-automation/gain' to '/'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-94]: [cmake]:[current]: 'None'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-94]: [cmake]:[generate new db]
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-94]: [db]:[get]: for file /home/gizdov/Git/pdqa-automation/gain/gain
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-94]: [db]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-94]: searching 'compile_commands.json' from '/home/gizdov/Git/pdqa-automation/gain' to '/'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-94]: [db]:[current]: 'None'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-94]: [db]:[load new]
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-94]: [db]:[no new]: return None
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-94]: [clang_complete_file]:[get]: for file /home/gizdov/Git/pdqa-automation/gain/gain.cpp
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-94]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-94]: searching '.clang_complete' from '/home/gizdov/Git/pdqa-automation/gain' to '/'
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-94]: [clang_complete_file]:[current]: 'None'
[ECC:DEBUG]:[bin_complete.py]:[run_clang_command]:[Thread-94]: clang command: 
['clang++', '-c', '-fsyntax-only', '-x', 'c++', '-std=c++11', '-I/usr/include', '-I/usr/include/root', '-I/opt/cuda/include', '-I/home/gizdov/$project_base_path/include', '-I/home/gizdov/$project_base_path/common/include', '-I/home/gizdov/$project_base_path/src', '-I/usr/lib/clang/$clang_version/include', '/tmp/EasyClangComplete/gain.cpp']
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-94]: command: 
clang++ -c -fsyntax-only -x c++ -std=c++11 -I/usr/include -I/usr/include/root -I/opt/cuda/include -I/home/gizdov/$project_base_path/include -I/home/gizdov/$project_base_path/common/include -I/home/gizdov/$project_base_path/src -I/usr/lib/clang/$clang_version/include /tmp/EasyClangComplete/gain.cpp
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-94]: clang process finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-94]: clang process output: 
/tmp/EasyClangComplete/gain.cpp:4:6: error: use of undeclared identifier 'Monitor'
void Monitor::readDatasheet(const TString &datasheet) {
     ^
/tmp/EasyClangComplete/gain.cpp:4:35: error: unknown type name 'TString'
void Monitor::readDatasheet(const TString &datasheet) {
                                  ^
/tmp/EasyClangComplete/gain.cpp:70:6: error: use of undeclared identifier 'Monitor'
void Monitor::readDatasheets(const TString &path) {
     ^
/tmp/EasyClangComplete/gain.cpp:70:36: error: unknown type name 'TString'
void Monitor::readDatasheets(const TString &path) {
                                   ^
4 errors generated.

[ECC:DEBUG]:[bin_complete.py]:[update]:[Thread-94]: rebuilding done in 0.07604813575744629 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-94]: generating error regions for view 208
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-94]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-94]: showing error regions: [(68, 75), (97, 104), (2614, 2621), (2644, 2651)]
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-94]: starting timer to remove old configs.
```

This is definitely a bug and it's really annoying. Some of the classes I work on a daily basis with trigger this parser bug and I basically need to kill EasyClangComplete to work with those files.

**Comment by kgizdov** [comment]
Still getting the error
```
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
error: 
        EasyClangComplete:
        "use_libclang" is false
        "show_type_info" is true.

        Unfortunately, there is no way to show type info
        if you are not using libclang.

        Please use libclang or set "show_type_info" to false.
        
ERROR:concurrent.futures:exception calling callback for <Future at 0x7feca1b26c50 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/gizdov/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 329, in info_finished
    (tooltip_request, result) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
error: 
        EasyClangComplete:
        "use_libclang" is false
        "show_type_info" is true.

        Unfortunately, there is no way to show type info
        if you are not using libclang.

        Please use libclang or set "show_type_info" to false.
        
ERROR:concurrent.futures:exception calling callback for <Future at 0x7feca810e810 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/gizdov/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 329, in info_finished
    (tooltip_request, result) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
error: 
        EasyClangComplete:
        "use_libclang" is false
        "show_type_info" is true.

        Unfortunately, there is no way to show type info
        if you are not using libclang.

        Please use libclang or set "show_type_info" to false.
        
ERROR:concurrent.futures:exception calling callback for <Future at 0x7fecb4064b10 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/gizdov/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 329, in info_finished
    (tooltip_request, result) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
```

**Comment by niosus** [comment]
Alright, It seems that the relevant line is this:
```
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-94]:  No cindex module for clang version:
```
There should be a version printed there. We cannot get that for a mysterious reason. I will have a look into this. Sorry for that.

One small thing. Judging from the logs you submitted, it seems that clang cannot be found every time after the trailing spaces package fails. Can you try to live some time without it to test if it has anything to do with it? I know it is superstitious, but it happens in every log you showed me :laughing:

**Comment by niosus** [comment]
@kgizdov could you please try to reproduce this without the TralingSpaces package?

**Comment by niosus** [comment]
Also, please submit the *full* log from the start of sublime text to the moment the error occurs.

**Comment by kgizdov** [comment]
@niosus OK, I will try and do it all this week.

**Comment by kgizdov** [comment]
I can't reproduce the bug anymore. Arch is now on `Clang 5.0` and the your plugin was updated, so maybe that fixed it. I will re-open if the problem resurfaces, but for the moment everything works fine with and without the `Trailing Spaces` package.
