### ISSUE TITLE
Cmake can't work when containing 'gbk' encoding 

### ISSUE THREAD

**Issue by tongxian** [niosus/EasyClangComplete#328]
I put CMakeLists.txt into my project , it occurs like below, it may be the reason that the CMakeLists.txt contains Chinese words as comment .

```
[ECC:DEBUG]:[tools.py]:[search]:[Thread-10]: found 'CMakeLists.txt' file: H:\SONA\svn\trunk\project\audiolib\effect2\CMakeLists.txt
ERROR:concurrent.futures:exception calling callback for <Future at 0x22aa44352b0 state=finished raised UnicodeDecodeError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 308, in config_updated
    log.debug("updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\view_config.py", line 357, in load_for_view
    res = self._cache[v_id].update_if_needed(view, settings)
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\view_config.py", line 83, in update_if_needed
    completer, flags = ViewConfig.__generate_essentials(view, settings)
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\view_config.py", line 176, in __generate_essentials
    flags += ViewConfig.__load_source_flags(view, settings, prefixes)
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\view_config.py", line 221, in __load_source_flags
    flags = flag_source.get_flags(view.file_name(), search_scope)
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\flags_sources\cmake_file.py", line 75, in get_flags
    current_cmake_path = self._find_current_in(search_scope, 'project')
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\flags_sources\flags_source.py", line 114, in _find_current_in
    search_content=search_content).full_path()
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\tools.py", line 335, in search
    search_content):
  File "H:\SOFTWARE\Portableapps\PortableApps\SublimeText\Data\Packages\EasyClangComplete\plugin\tools.py", line 361, in contains
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 4: illegal multibyte sequence
```

**when I remove all Chinese comment, it work well , but another issue happens,** 

```
CMake Warning (dev) at CMakeLists.txt:38 (add_executable):
  Policy CMP0038 is not set: Targets may not link directly to themselves.
  Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Target "t1" links to itself.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: C:/Users/Public/Documents/Wondershare/CreatorTemp/EasyClangComplete/cmake_builds/ca50011550a815f4ad02e443dbcde42a

[ECC:ERROR]:[cmake_file.py]:[__compile_cmake]:[Thread-72]: cmake has finished, but no compilation database.
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-72]: [db]:[get]: for file h:\sona\svn\trunk\project\audiolib\effect2\tiaudio
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-72]: [db]:[cached]: 'None'
```

**It says no database , and cmake will always complie while changing another source file. 
How could I solve the problom?**

**Comment by niosus** [comment]
Hm, I don't really know how to deal with Chinese comments. I will need to do a search on how to overcome this issue. As for the situation when you remove those make sure that you clear the cmake cache. There is a command in this plugin for that.

**Comment by tongxian** [comment]
@niosus thank you for your help, I find the problem is cmake's generator is Visual Studio 2013, and it can't generate the database. I try to modify the user settings like this,
`  "verbose" : false,
  "cmake":[
    {"-G": "MSYS Makefiles"},
    {"generator": "MSYS Makefiles"},
  ]`
both can't work, still generate the vs project.
how can I config the setting to "MSYS Makefiles" ?

**Comment by niosus** [comment]
Unfortunately, I do not know much about development under Windows. You can try to continue the conversation in #175 

Is this issue still valid? Was the chinese symbol the problem? If not, could you please close it?
