### ISSUE TITLE
Plugin crashes when using CMakelists value in the flag_sources 

### ISSUE THREAD

**Issue by brupelo** [niosus/EasyClangComplete#329]
When using CMakelists flag, on [cmake_file](https://github.com/niosus/EasyClangComplete/blob/master/plugin/flags_sources/cmake_file.py#L175) suprocess.check_output will spawn  `OSError: [WinError 6] The handle is invalid` because stdin=None instead of being subprocess.PIPE.

This has already happened few times in other files in the past, so I guess to avoid this issue again in the future is better to wrap subprocess.check_output to become "platform independent" and use just that as an intermediate layer, i.e:

    def subprocess_check_output(cmd, stderr, shell, cwd, startupinfo, env, stdin=None):
        if platform.system() == "Windows":
            # Don't let console window pop-up briefly.
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = subprocess.SW_HIDE
            stdin = subprocess.PIPE

        return subprocess.check_output(
            cmd,
            stdin=stdin,
            stderr=stderr,
            shell=shell,
            cwd=cwd,
            env=env,
            startupinfo=startupinfo).decode('utf8').split()

That said, even when fixing this issue, the plugin will still crash [here](https://github.com/niosus/EasyClangComplete/blob/master/plugin/flags_sources/cmake_file.py#L180)

One example of the output returned by check_output is `['--', 'Configuring', 'done', '--', 'Generating', 'done', '--', 'Build', 'files', 'have', 'been', 'written', 'to:', 'C:/Users/BPL/AppData/Local/Temp/EasyClangComplete/cmake_builds/83ebc924f22036c0c0bb9a3f1cb8644a']`

And the traceback is:

    ERROR:concurrent.futures:exception calling callback for <Future at 0x13ebc3c8 state=finished raised TypeError>
    Traceback (most recent call last):
      File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 308, in config_updated
        log.debug("updated config: %s", future.result())
      File "./python3.3/concurrent/futures/_base.py", line 394, in result
      File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
      File "./python3.3/concurrent/futures/thread.py", line 54, in run
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 360, in load_for_view
        config = ViewConfig(view, settings)
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 60, in __init__
        completer, flags = ViewConfig.__generate_essentials(view, settings)
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 176, in __generate_essentials
        flags += ViewConfig.__load_source_flags(view, settings, prefixes)
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\plugin\view_config.py", line 221, in __load_source_flags
        flags = flag_source.get_flags(view.file_name(), search_scope)
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\plugin\flags_sources\cmake_file.py", line 121, in get_flags
        flags=self.__cmake_flags)
      File "D:\software\SublimeText 3_x64\Data\Packages\EasyClangComplete\plugin\flags_sources\cmake_file.py", line 199, in __compile_cmake
        output_text = ''.join(map(chr, output))
    TypeError: an integer is required (got type str)

**Comment by brupelo** [comment]
Added a PR [here](https://github.com/niosus/EasyClangComplete/pull/330). Although it'd be convenient to use the "multiplatform" check_output (or one better than the provided one) all over the repo.

**Comment by niosus** [comment]
Thanks for reporting and for the PR. I will try my best to merge it but only next week. This week I will definitely have no time to have any meaningful look into it. Sorry for the delay.

**Comment by Seppone** [comment]
By far I am not an python expert. but I solved an similiar problem by calling `subprocess.check_output` with `stdin=subprocess.DEVNULL`.
