### ISSUE TITLE
show_type_info error always pop out

### ISSUE THREAD

**Issue by OptimusPrimeCao** [niosus/EasyClangComplete#440]
# System info: #
- Which system are you on: `osx`
- Clang version: `Apple LLVM version 7.0.2 (clang-700.1.81)`

# What happens:  #

error: 
        
        EasyClangComplete:
        "use_libclang" is false
        "show_type_info" is true.
        Unfortunately, there is no way to show type info
        if you are not using libclang.
        Please use libclang or set "show_type_info" to false.

<details>
<summary>Log that illustrates the issue: </summary>
  
```

[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 7.0 reported. Reducing it to 3.7.
[ECC:INFO   ]: Found clang version 3.7
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
Package Control: Skipping automatic upgrade, last run at 2018-03-06 18:12:58, next run at 2018-03-06 19:12:58 or after
environment variables loaded using: /bin/zsh -l
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 7.0 reported. Reducing it to 3.7.
[ECC:INFO   ]: Found clang version 3.7
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
Unable to fetch update url contents
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 7.0 reported. Reducing it to 3.7.
[ECC:INFO   ]: Found clang version 3.7
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 7.0 reported. Reducing it to 3.7.
[ECC:INFO   ]: Found clang version 3.7
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 7.0 reported. Reducing it to 3.7.
[ECC:INFO   ]: Found clang version 3.7
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

ERROR:concurrent.futures:exception calling callback for <Future at 0x10a12a350 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/Users/caoyt/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 408, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

ERROR:concurrent.futures:exception calling callback for <Future at 0x109fc25d0 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/Users/caoyt/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 408, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.2/../../libclang.dylib'
[ECC:ERROR  ]: error: dlsym(0x7fb6048c4360, clang_Cursor_isAnonymous): symbol not found. Please ensure that your python bindings are compatible with your libclang.so version.
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
```

</details>

**Comment by niosus** [comment]
Please, next time follow the issue template precisely. It takes so much time to understand an issue when it is malformed. I have fixed the formatting for you this time, but I will just close malformed issues in the future.

As for the issue at hand, it seems that apple clang 7.0 is reduced to LLVM clang 3.7 in the code and these bindings seem to be wrong.

I would like to ask you to change line: https://github.com/niosus/EasyClangComplete/blob/master/plugin/tools.py#L34 to point to version 3.8 or later. Let's see if this solves the issue.

**Comment by OptimusPrimeCao** [comment]
@niosus 
Thanks for your quick reply and sorry for that malformed format! It will not happen next time!  
Change to 3.8 does fix this problem. 😊
Can you explain why needs to do this?
And what do you mean by this "apple clang 7.0 is reduced to LLVM clang 3.7"
Thanks again!

**Comment by niosus** [comment]
Sure, happy to help. I will update the code to avoid this error for others in the future.

What do you mean by "the error is still in log"? Can you copy it here?

> And what do you mean by this "apple clang 7.0 is reduced to LLVM clang 3.7"

This is just the way I think about clang. Apple clang has their own naming scheme. The libclang python bindings I use are from LLVM clang, so I need to translate the version number from Apple clang to LLVM clang using [some table](https://en.wikipedia.org/wiki/Xcode#Latest_versions). It appears that the table is wrong and clang 7.0 actually translates to clang 3.8 or there is another bug :)

**Comment by niosus** [comment]
Oh, so then it is not fixed at all! This means there is no easy fix. What about changing the clang version to an older one? 3.6 instead of original 3.7?

**Comment by OptimusPrimeCao** [comment]
After change it to 3.6 the error in log becomes:
[ECC:ERROR  ]: cmake has finished, but no compilation database.
What does it mean?
And there is anyway I can use kind of 'jump to definition' function with this plugin? Or any other?

**Comment by niosus** [comment]
Can you post the full log just like in the issue statement so that I am sure what is happening? I need more information to answer this. As for "jump to definition" our best bet is sublime's own index as it is hard to do with libclang. See #124 for more details.

**Comment by OptimusPrimeCao** [comment]
<details>
<summary>Log that illustrates the issue: </summary>
  
```

plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-03-16 09:51:10, next run at 2018-03-16 10:51:10 or after
environment variables loaded using: /bin/zsh -l
Unable to fetch update url contents
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 9.0 reported. Reducing it to 4.0.
[ECC:INFO   ]: Found clang version 4.0
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/../../libclang.dylib'
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 9.0 reported. Reducing it to 4.0.
[ECC:INFO   ]: Found clang version 4.0
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 9.0 reported. Reducing it to 4.0.
[ECC:INFO   ]: Found clang version 4.0
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 9.0 reported. Reducing it to 4.0.
[ECC:INFO   ]: Found clang version 4.0
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: cmake has finished, but no compilation database.
```

**Comment by niosus** [comment]
Probably there is an error with cmake. Please make sure you take the log with `verbose` option of the plugin on. It becomes much more verbose then.

**Comment by OptimusPrimeCao** [comment]
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:WARNING]: OSX version 9.0 reported. Reducing it to 4.0.
[ECC:INFO   ]: Found clang version 4.0
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: found libclang library file: '/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/../../libclang.dylib'
[ECC:ERROR  ]: 
Your source generated settings define too many std flags:
[(-std=c++11), (-std=gnu++11)]

Please fix your settings.

Package Control: Skipping automatic upgrade, last run at 2018-03-27 14:01:44, next run at 2018-03-27 15:01:44 or after
environment variables loaded using: /bin/zsh -l
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: 
Your source generated settings define too many std flags:
[(-std=c++11), (-std=gnu++11)]

Please fix your settings.

Unable to fetch update url contents
[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: 
Your source generated settings define too many std flags:
[(-std=c++11), (-std=gnu++11)]

Please fix your settings.

[ECC:INFO   ]: init completer based on libclang
[ECC:ERROR  ]: 
Your source generated settings define too many std flags:
[(-std=c++11), (-std=gnu++11)]

Please fix your settings.

Here is my error log now!
