### ISSUE TITLE
failure to retrieve popup with type information

### ISSUE THREAD

**Issue by nolange** [niosus/EasyClangComplete#449]
# System info: #
- Sublime Text version: Version 3.0, Build 3143
- Which system are you on: Debian 'buster' 4.14.0-3-amd64
- Clang version: 5.0.1

# What happens:  #

Following code shows this, when hovering over CParams: "MDPopups failed to create the popup/phantom"

```c
struct CParams
{
    unsigned m_Set;
    unsigned m_Clear;
};

static struct CParams parseCmdline(int argc, char **argv)
{
    struct CParams r;
    return r;
}
```

I haven't been able to fully narrow it down, sometimes it works after removing the static keyword,
sometimes later References to struct CParams show a correct popup.
Other times nothing works.

<details>
<summary>Log that illustrates the issue: </summary>
  
```
DPI scale: 1
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/lano/.config/sublime-text-3/Packages
state path: /home/lano/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/lano/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
"Packages/Color Scheme - Default/Cobalt.tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"
pre session restore time: 0.055344
loading dictionary Packages/Language - German/German_de_DE.dic
startup time: 0.153691
first paint time: 0.156044
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin CMake.AutoComplete
reloading plugin Clang Format.clang_format
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pandoc.Pandoc
reloading plugin VimModelines.vimmodelines
reloading plugin EasyClangComplete.EasyClangComplete
plugins loaded
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[MainThread]: on_activated_async view id 25
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 25. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[MainThread]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I$project_base_path/src' to '-I/src'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/5.0.1/include'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[MainThread]: settings initialized for view: 25
Loaded VimModelines
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-5]: generate new config for path: 25
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-5]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-5]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: platform: ('64bit', '')
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: python version: 3.3.6
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: we are on 'Linux'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: user provided libclang_path: <some_path_here>
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: searching for: 'libclang-$version.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: libclang search output = 'libclang-5.0.so'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-5]: real output: libclang-5.0.so
[ECC:WARNING]:[utils.py]:[find_libclang_dir]:[Thread-5]:  clang could not find 'libclang-5.0.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: searching for: 'libclang.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: libclang search output = 'libclang.so'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-5]: real output: libclang.so
[ECC:WARNING]:[utils.py]:[find_libclang_dir]:[Thread-5]:  clang could not find 'libclang.so'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: searching for: 'libclang-$version.so.1'
[ECC:DEBUG]:[utils.py]:[find_libclang_dir]:[Thread-5]: libclang search output = '/usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../x86_64-linux-gnu/libclang-5.0.so.1'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-5]: real output: /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../x86_64-linux-gnu/libclang-5.0.so.1
[ECC:INFO]:[utils.py]:[find_libclang_dir]:[Thread-5]: found libclang library file: '/usr/lib/x86_64-linux-gnu/libclang-5.0.so.1'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: [cmake]:[get]: for file /media/HIPASE_X/des/untitled.c
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'CMakeLists.txt' from '/media/HIPASE_X/des' to '/'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: [cmake]:[current]: 'None'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: [cmake]:[generate new db]
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[get]: for file /media/HIPASE_X/des/untitled.c
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'compile_commands.json' from '/media/HIPASE_X/des' to '/'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[current]: 'None'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[load new]
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[no new]: return None
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-5]: [CppProperties]:[get]: for file /media/HIPASE_X/des/untitled.c
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-5]: [CppProperties]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'CppProperties.json' from '/media/HIPASE_X/des' to '/'
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-5]: [CppProperties]:[current]: 'None'
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-5]: [c_cpp_properties]:[get]: for file /media/HIPASE_X/des/untitled.c
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-5]: [c_cpp_properties]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'c_cpp_properties.json' from '/media/HIPASE_X/des' to '/'
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-5]: [c_cpp_properties]:[current]: 'None'
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-5]: [clang_complete_file]:[get]: for file /media/HIPASE_X/des/untitled.c
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-5]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching '.clang_complete' from '/media/HIPASE_X/des' to '/'
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-5]: [clang_complete_file]:[current]: 'None'
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: view is 25
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: translation unit does not exist. Creating.
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-5]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c', '-std=c11', '-I/usr/include', '-I/src', '-I/usr/lib/clang/5.0.1/include', '-I/media/HIPASE_X/des', '-I/media/HIPASE_X']
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-5]: compilation started for view id: 25
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-5]: compilation done in 0.004778861999511719 seconds
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: reparsing translation_unit for view 25
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: reparsed in 0.014071941375732422 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-5]: generating error regions for view 25
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-5]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-5]: showing error regions: []
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-5]: updated config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7ff30b3878d0>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-5]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-5]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7ff30b3878d0>
mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Failed to get Sublime highlighter object!
mdpopups: Traceback (most recent call last):
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 630, in show_popup
    nl2br=nl2br, allow_code_wrap=allow_code_wrap
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 322, in _create_html
    allow_code_wrap=allow_code_wrap
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 435, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"').replace('\n', '')
  File "/home/lano/.config/sublime-text-3/Packages/python-markdown/st3/markdown/__init__.py", line 368, in convert
    self.lines = prep.run(self.lines)
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 500, in run
    lines = self.search_nested(lines)
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 420, in search_nested
    self.eval(m, start, end)
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 310, in eval
    self.process_nested_block(m, start, end)
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 349, in process_nested_block
    code = entry["formatter"](self.rebuild_block(self.code), self.lang)
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/superfences.py", line 467, in highlight
    linespecial=linespecial
  File "/home/lano/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 324, in highlight
    code = self.sublime_hl[1].syntax_highlight(
AttributeError: 'NoneType' object has no attribute 'syntax_highlight'

Package Control: Skipping automatic upgrade, last run at 2018-04-11 10:45:02, next run at 2018-04-11 11:45:02 or after
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7ff30b3878d0>
[ECC:DEBUG]:[popup_error_vis.py]:[show_popup_if_needed]:[Dummy-8]: no error regions for row: 13
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7ff30b3878d0>
[ECC:DEBUG]:[popup_error_vis.py]:[show_popup_if_needed]:[Dummy-8]: no error regions for row: 13
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[view_config.py]:[__remove_old_configs]:[Thread-4]: Skip young config: Age 20.28484559059143 < 1800. View: 25.
```

</details>

**Comment by niosus** [comment]
That is interesting. I will have a look at it during this week. Maybe I am feeding something wrong into the mdpopups.

**Comment by nolange** [comment]
Sorry, does not seem to be related to ECC, but to this: `"Packages/Color Scheme - Default/Cobalt.tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"`.

The default color scheme works fine, and for the first time I see the definitions in the popups.

Thanks for the plugin btw.

**Comment by niosus** [comment]
Cool, great that is is solved. :) And thanks! I wish I had more time on it though...
