### ISSUE TITLE
use_libclang popup

### ISSUE THREAD

**Issue by monouser7dig** [niosus/EasyClangComplete#498]
# System info: #
- Sublime Text version: `3175`
- Which system are you on: `macOS 10.13.6`
- Clang version: `7.0` via homebrew

# What happens:  #
Describe your issue here.
ECC gives me a popup and has an issue 
<img width="532" alt="bildschirmfoto 2018-09-22 um 13 51 19" src="https://user-images.githubusercontent.com/26345163/45916989-14897480-be6f-11e8-9000-6bd959713480.png">
  

logs, please ask if something is missing, whole logs contain a ton of private config which would take time to go through, I think this is where it goes wrong
```
[ECC:DEBUG]:[bin_complete.py]:[run_clang_command]:[Thread-11]: clang command: 
['clang++', '-c', '-fsyntax-only', '-x', 'c++', '-I/usr/include', '-I~/foo/bar/src', '-I/usr/lib/clang/7.0.0/include', '-I~/foo/bar', '-I~/foo/bar/lib/i_net', '-I~/foo/bar/lib', 'c++', '-I~/foo/bar/debug/lib/i_net/lib@i_net@@i_net@sta', '-I~/foo/bar/debug/lib/i_net', '-I~/foo/bar/include', '-Xclang', '-fcolor-diagnostics', '-fsanitize=address,undefined', '-fno-omit-frame-pointer', '-pipe', '-Wall', '-Winvalid-pch', '-Wnon-virtual-dtor', '-Wextra', '-Wpedantic', '-std=c++1z', '-O0', '-g', '-Weverything', '-Wno-c++98-compat', '-Wno-c++98-compat-pedantic', '-Wno-padded', '-Wno-shadow-field-in-constructor', '-MD', '-MQ', 'lib/i_net/lib@i_net@@i_net@sta/i_net.cpp.o', '-MF', 'lib/i_net/lib@i_net@@i_net@sta/i_net.cpp.o.d', '/var/folders/87/_q0y4x3s5452phzylhlzk6400000gn/T/EasyClangComplete/i_net.cpp']
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-11]: command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-11]: command output: 
clang-7: error: no such file or directory: 'c++'







Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

exception calling callback for <Future at 0x10d1a3290 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "~/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 434, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-8]: on_activated_async view id 25
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-11]: config exists for path: 25
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-11]: init completer based on libclang
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-11]:  No cindex module for clang version: 7.0.0
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-11]: cannot initialize completer with libclang.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-11]: falling back to using clang in a subprocess.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-11]: init completer based on clang from cmd
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[get]: for file ~/foo/bar/lib/i_net/i_net.cpp
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[cached]: '~/foo/bar/debug/compile_commands.json'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-11]: searching 'compile_commands.json' from '~/foo/bar/debug' to '/'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-11]: found 'compile_commands.json' file: ~/foo/bar/debug/compile_commands.json
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[current]: '~/foo/bar/debug/compile_commands.json'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]: found cached compile_commands.json
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[load cached]
[ECC:DEBUG]:[tools.py]:[update_mod_time]:[Thread-11]: updating modification time for file '~/foo/bar/debug/compile_commands.json'
[ECC:DEBUG]:[view_config.py]:[__load_source_flags]:[Thread-11]: flags generated from 'compile_commands.json'.
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-11]: Removing default std flag: '-std=c++11' in favor of: '-std=c++1z'
[ECC:DEBUG]:[view_config.py]:[needs_update]:[Thread-11]: view config needs no update.
[ECC:DEBUG]:[view_config.py]:[needs_reparse]:[Thread-11]: view config needs no reparse.
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-11]: updated config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x10d140e90>
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x10d140e90>
[ECC:DEBUG]:[popup_error_vis.py]:[show_popup_if_needed]:[Dummy-8]: no error regions for row: 35
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Dummy-8]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x10d140e90>
[ECC:DEBUG]:[popup_error_vis.py]:[show_popup_if_needed]:[Dummy-8]: no error regions for row: 35
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-11]: config exists for view: 25
[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-11]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x10d140e90>
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

exception calling callback for <Future at 0x10e9b5c90 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "~/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 434, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-8]: on_activated_async view id 25
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-11]: config exists for path: 25
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-11]: init completer based on libclang
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-11]:  No cindex module for clang version: 7.0.0
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-11]: cannot initialize completer with libclang.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-11]: falling back to using clang in a subprocess.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-11]: init completer based on clang from cmd
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[get]: for file ~/foo/bar/lib/i_net/i_net.cpp
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[cached]: '~/foo/bar/debug/compile_commands.json'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-11]: searching 'compile_commands.json' from '~/foo/bar/debug' to '/'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-11]: found 'compile_commands.json' file: ~/foo/bar/debug/compile_commands.json
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[current]: '~/foo/bar/debug/compile_commands.json'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]: found cached compile_commands.json
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-11]: [db]:[load cached]
[ECC:DEBUG]:[tools.py]:[update_mod_time]:[Thread-11]: updating modification time for file '~/foo/bar/debug/compile_commands.json'
[ECC:DEBUG]:[view_config.py]:[__load_source_flags]:[Thread-11]: flags generated from 'compile_commands.json'.
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-11]: Removing default std flag: '-std=c++11' in favor of: '-std=c++1z'
[ECC:DEBUG]:[view_config.py]:[needs_update]:[Thread-11]: view config needs no update.
[ECC:DEBUG]:[view_config.py]:[needs_reparse]:[Thread-11]: view config needs no reparse.
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-11]: updated config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x10d140e90>

```

my custom settings, rest default, especially `"use_libclang" : true,` I did not overwrite it in the custom config 
```json
 {
  "common_flags":[
    // some example includes
    "-I/usr/include",
    "-I$project_base_path/src",
    // this is needed to include the correct headers for clang
    "-I/usr/lib/clang/$clang_version/include",
    "-I$project_base_path",
  ],

  "flags_sources": [
    {"file": "compile_commands.json", "search_in": "$project_base_path/debug"},

  ],
  "cpp_flags" : [ "-std=c++17" ],
  "hide_default_completions": true,
  "verbose" : true,
}
```

hope this issue helps

**Comment by niosus** [comment]
This looks weird. But then most of the issues do :smile: 
Anyway, the first line seems to already be related to an attempt to use non-libclang version. This means that something has already failed and the system is trying to use clang binary. The error I am interested in is somewhere close to the startup of the plugin and is missing from the log you posted. Also, please, use the `<details>` tags to hide verbose outputs. This makes life of anyone who reads the issue later easier.

**Comment by monouser7dig** [comment]
> This looks weird. But then most of the issues do

👍 👍 

> Also, please, use the <details> tags to hide verbose outputs.

yes, sorry, already thought I'd missed something like that

this should be the first output of ECC:
<details>

```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:ERROR  ]: Cannot recognize language from syntax: 'JSON'
[ECC:ERROR  ]: Cannot recognize language from syntax: 'JSON'
[ECC:ERROR  ]: Cannot recognize language from syntax: 'JSON'
[ECC:ERROR  ]: Cannot recognize language from syntax: 'JSON'
[ECC:ERROR  ]: Cannot recognize language from syntax: 'JSON'
reloading settings Packages/User/EasyClangComplete.sublime-settings
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:INFO]:[settings_manager.py]:[on_settings_changed]:[MainThread]: settings changed and reloaded
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[MainThread]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[MainThread]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[MainThread]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-8]: view file_name is None
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-8]: no settings for view 66. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-8]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-8]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-8]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-8]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-8]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-8]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-8]: populated '-I$project_base_path/src' to '-I/~/foo/src'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-8]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/7.0.0/include'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-8]: populated '-I$project_base_path' to '-I/~/foo'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-8]: populated '$project_base_path/debug' to '/~/foo/debug'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-8]: populated '~/some_folder/*' to '/~/some_folder/*'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-8]: populated '$project_base_path/some/project/path/*' to '/~/foo/some/project/path/*'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-8]: settings initialized for view: 66
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-8]: on_activated_async view id 66
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-24]: generate new config for path: 66
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-24]: init completer based on libclang
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-24]:  No cindex module for clang version: 7.0.0
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-24]: cannot initialize completer with libclang.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-24]: falling back to using clang in a subprocess.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-24]: init completer based on clang from cmd
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-24]: [db]:[get]: for file /~/foo/lib/i_net/i_net.cpp
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-24]: [db]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-24]: searching 'compile_commands.json' from '/~/foo/debug' to '/'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-24]: found 'compile_commands.json' file: /~/foo/debug/compile_commands.json
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-24]: [db]:[current]: '/~/foo/debug/compile_commands.json'
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-24]: [db]:[load new]
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-24]: Getting default flags for ('ccache', 'c++1z', 'c++')
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-24]: Querying compiler for defaults
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-24]: command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-24]: command output: 
ccache: invalid option -- x
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)

Options:
    -c, --cleanup         delete old files and recalculate size counters
                          (normally not needed as this is done automatically)
    -C, --clear           clear the cache completely (except configuration)
    -F, --max-files=N     set maximum number of files in cache to N (use 0 for
                          no limit)
    -M, --max-size=SIZE   set maximum size of cache to SIZE (use 0 for no
                          limit); available suffixes: k, M, G, T (decimal) and
                          Ki, Mi, Gi, Ti (binary); default suffix: G
    -o, --set-config=K=V  set configuration key K to value V
    -p, --print-config    print current configuration options
    -s, --show-stats      show statistics summary
    -z, --zero-stats      zero statistics counters

    -h, --help            print this help text
    -V, --version         print version and copyright information

See also <https://ccache.samba.org>.
```

**Comment by niosus** [comment]
Ok, I think I see the issue. It is written here:
```
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-24]:  No cindex module for clang version: 7.0.0
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-24]: cannot initialize completer with libclang.
```
This is related to #472 I guess.

Also, you seem to be using ccache and this also caused some issues as in #475 

To try to fix the first issue, can you try to add the last value
```
'7.0': PKG_NAME + ".plugin.clang.cindex50",  # FIXME
```
to https://github.com/niosus/EasyClangComplete/blob/54c5274b4bb7ca5d8f24bab6e6a172966face675/plugin/completion/lib_complete.py#L26-L38

This should add a fallback to the older `cindex` and might fix your first issue.

**Comment by monouser7dig** [comment]
Ok so would you want me to try the workaround and report back?
Because I see the other two issues are merged/ solved/ postponed?
If so, can I just crawl for it in my sublime folder somewhere or would I have to clone this and do some manuell install?... I‘d need to look thorough this because I‘m not doing sublime dev.

I can at least say that ccache did not cause trouble before I upgraded to clang 7 and Mojave.
And I was admittedly happy that I found a cpp completion that worked so that was really nice 👍🏼

**Comment by kgizdov** [comment]
I have the same bug on ArchLinux with Clang 7.0.0 and adding:
```python
'7.0': PKG_NAME + ".plugin.clang.cindex50",  # FIXME
```
to `lib_complete.py`:
```python
# lib_complete.py
cindex_dict = {
    '3.2': PKG_NAME + ".plugin.clang.cindex32",
    '3.3': PKG_NAME + ".plugin.clang.cindex33",
    '3.4': PKG_NAME + ".plugin.clang.cindex34",
    '3.5': PKG_NAME + ".plugin.clang.cindex35",
    '3.6': PKG_NAME + ".plugin.clang.cindex36",
    '3.7': PKG_NAME + ".plugin.clang.cindex37",
    '3.8': PKG_NAME + ".plugin.clang.cindex38",
    '3.9': PKG_NAME + ".plugin.clang.cindex39",
    '4.0': PKG_NAME + ".plugin.clang.cindex40",
    '5.0': PKG_NAME + ".plugin.clang.cindex50",
    '6.0': PKG_NAME + ".plugin.clang.cindex50",  # FIXME
    '7.0': PKG_NAME + ".plugin.clang.cindex50",  # FIXME
}
```
seems to work fine. No more errors.

**Comment by monouser7dig** [comment]
works for me too

**Comment by niosus** [comment]
Great! I will push this fix in a couple of days along with other minor fixed for how we handle clang 7.
