### ISSUE TITLE
file not found when searching for libclang

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#52]
@pl-ca reported:

When I launch ST3 after installing the plug-in I get an error related to some file not found. Am I missing something?
```
reloading plugin test-complete-plugin.script
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\script.py", line 14, in <module>
    clang_dir = ClangUtils.find_libclang_dir("clang++")
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\utils.py", line 62, in find_libclang_dir
    get_library_path_cmd).decode('utf8').strip()
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

Moving here from #4

**Comment by pl-ca** [comment]
I'm not sure if I was clear but this happened when I attempted to run https://github.com/niosus/test-complete-plugin and not EasyClangComplete.

**Comment by niosus** [comment]
Ah, ok, I got it. I will move it there then. Maybe something is wrong there. I will close this issue here then.
