### ISSUE TITLE
Cannot get ECC to work on windows

### ISSUE THREAD

**Issue by morcillo** [niosus/EasyClangComplete#575]
# System info: #
Windows 10 64 bit
- Sublime Text version: `3.2 build 3200`
- Clang version: <clang version 8.0.0 (tags/RELEASE_800/final)
                           Target: x86_64-pc-windows-msvc
                           Thread model: posix
                           InstalledDir: C:\Program Files\LLVM\bin>

# What happens:  #
I simply cannot get EasyClangComplete to work on my configuration. At the moment I am programming for a Cortex M3 microcontroller from ST. 

<details>
<summary>EasyClangComplete does not autocomplete </summary>

I've been trying to configure ECC to work in windows 10 and I am programming a Cortex M microcontroller. I tried creating a simple structure and right below it I create a variable with the struct's type and then try to autocomplete and nothing happens. At most I can get to do a full autocomplete with every single word IN THE FILE I'M CURRENTLY USING, it doesn't even give me the correct autocomplete options at first, I have to scrool to get to them and it doesn't even offer to autocomplete from any other files. I have created a configuration in the project settings:
```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
    	"easy_clang_complete_verbose": true,
        "ecc_use_libclang": true,
        "clang_flags": [
        "-std=c11", "-I/usr/include", "-IC:\\Program Files (x86)\\Atollic\\TrueSTUDIO for STM32 9.2.0\\ARMTools\\lib\\gcc\\arm-atollic-eabi\\6.3.1\\include", "-IInc"
        ], 
        "common_flasg": [
        	"C:\\Program Files (x86)\\Atollic\\TrueSTUDIO for STM32 9.2.0\\ARMTools\\lib\\gcc\\arm-atollic-eabi\\6.3.1\\include", "-IInc"
        ],
        "file": ".clang_complete", 
        "verbose": true
    }
}
```
 

The log file is as follows:
```
[ECC:INFO   ]: Getting version from command: ` -v`
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\userName\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "C:\Users\userName\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "C:\Users\userName\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "C:\Users\userName\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "C:\Users\userName\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "C:\Users\userName\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable
```

</details>

**Comment by niosus** [comment]
Please try to capture the log with verbose. I see that you have it in project settings, but make sure that the file you have opened is part of the project. It seems that verbose option does not work for some reason.

Also, `common_flags` is misspelled and you have to use the `ecc_` prefix for all settings related to ECC in your project settings. Also, there is not setting `clang_flags` in ECC. Please refer to the docs site for proper settings.

**Comment by morcillo** [comment]
Wow, youn answrered very fast. I was expecting a response in a few days maybe, so thank you for your quick response. 

Ok, I've fixed the common_flags and now I get a debug output. I also changed the removed clang_flags from the options and I removed the .clang_complete file and now I at least get a debug output and it at least tries to autocomplete ... I can autocomplete easily for the name of the variable, but it can't autocomplete a struct that's right above it. Proably this is happening due to a problem in my configuration. 

From the recent behaviour I can see the following things:

- It can't find a file that is in the -IInc folder that is in the project;
- It can't find the definition to structures that are in the -IDrivers\\STM32F4xx_HAL_Driver\\Inc folder;
- It knows that I'm using a macro that is defined in a file inside the -Iinc folder (I hover over it and it correctly gives me the line that it is defined), but it give me a warning that I'm using a macro that is not defined;

I think that the errors are just propagating due to the first error (cannot find file in Inc folder) and that's why I'm getting a strange behaviour, but I can't see what I'm doing wrong. The file is inside the folder, the folder is part of the project. Maybe the debug output can give you a better idea of what I'm facing. 

This is my new configuration (I used Makefile for the file configuration , but I don't have a makefile in the project):
```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
    	"easy_clang_complete_verbose": true,
        "ecc_use_libclang": true,
        "common_flags": [
        	"-IC:\\Program Files (x86)\\Atollic\\TrueSTUDIO for STM32 9.2.0\\ARMTools\\lib\\gcc\\arm-atollic-eabi\\6.3.1\\include", "-IInc",
            "-IDrivers\\STM32F4xx_HAL_Driver\\Inc",
            "-IDrivers\\CMSIS\\Include",
            "-IDrivers\\CMSIS\\Device\\ST\\STM32F4xx\\Include",
        ],
        "file": "Makefile", 
        "verbose": true
    }
}
```

And this is the output debug:
```
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 72. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: use_libclang               <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: verbose                    <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[MainThread]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I$project_base_path/src' to '-IC:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3/src'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/8.0.0/include'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '~/some_folder/*' to 'C:\Users\username/some_folder/*'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[MainThread]: populated '$project_base_path/some/project/path/*' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3/some/project/path/*'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[MainThread]: settings initialized for view: 72
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[MainThread]: on_activated_async view id 72
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[MainThread]: view file_name does not exist in system
[ECC:DEBUG]:[EasyClangComplete.py]:[on_close]:[MainThread]: closing view 72
[ECC:DEBUG]:[settings_manager.py]:[clear_for_view]:[MainThread]: clearing settings for view: 72
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[MainThread]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Thread-5]: view file_name is None
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-5]: view <sublime.View object at 0x000002044F5ACE10> is not valid. Cannot get config.
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-5]: updated config: None
[ECC:DEBUG]:[view_config.py]:[clear_for_view]:[Thread-5]: trying to clear config for view: 72
[ECC:DEBUG]:[EasyClangComplete.py]:[config_removed]:[Thread-5]: removed config for id: 72
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-6]: no settings for view 28. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: use_libclang               <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: verbose                    <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-6]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-6]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '-I$project_base_path/src' to '-IC:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3/src'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/8.0.0/include'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '~/some_folder/*' to 'C:\Users\username/some_folder/*'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '$project_base_path/some/project/path/*' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3/some/project/path/*'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-6]: settings initialized for view: 28
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-6]: ECC does nothing for language syntax: 'JSON'
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-6]: ECC does nothing for language syntax: 'JSON'
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-6]: no settings for view 25. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: use_libclang               <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: verbose                    <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-6]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-6]: populating common_flags with current variables.
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '-I$project_base_path/src' to '-IC:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3/src'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '-I/usr/lib/clang/$clang_version/include' to '-I/usr/lib/clang/8.0.0/include'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '~/some_folder/*' to 'C:\Users\username/some_folder/*'
[ECC:DEBUG]:[settings_storage.py]:[__replace_wildcard_if_needed]:[Dummy-6]: populated '$project_base_path/some/project/path/*' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3/some/project/path/*'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-6]: settings initialized for view: 25
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-6]: on_activated_async view id 25
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-5]: generate new config for path: 25
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-5]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-5]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: Platform: Windows, ('64bit', 'WindowsPE')
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: Python version: 3.3.6
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: User provided libclang_path: '<some_path_here>'
[ECC:DEBUG]:[utils.py]:[get_folder_and_name]:[Thread-5]: User provided wrong libclang path: '<some_path_here>'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: Searching for: 'libclang.dll'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: Generating search folder
Package Control: Skipping automatic upgrade, last run at 2019-03-23 14:46:40, next run at 2019-03-23 15:46:40 or after
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: Libclang search output = 'C:\Program Files\LLVM\bin\clang'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-5]: real output: C:\Program Files\LLVM\bin\clang
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-5]: architecture: ('64bit', 'WindowsPE')
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-5]: folder to search: C:\Program Files\LLVM\bin\clang\..
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-5]: Checking path: C:\Program Files\LLVM\bin\libclang.dll
[ECC:INFO]:[utils.py]:[find_libclang]:[Thread-5]: Found libclang library file: 'C:\Program Files\LLVM\bin\libclang.dll'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: [cmake]:[get]: for file C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src\main.c
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'CMakeLists.txt' from 'C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3'
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-5]: No CMakeLists.txt file with 'project' in it found.
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[get]: for file c:\users\username\repositories\workspace\ledbarpretty_v1.3\src\main.c
[ECC:DEBUG]:[compilation_db.py]:[get_flags]:[Thread-5]: [db]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'compile_commands.json' from 'C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3'
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-5]: [CppProperties]:[get]: for file C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src\main.c
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-5]: [CppProperties]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'CppProperties.json' from 'C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3'
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-5]: [c_cpp_properties]:[get]: for file C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src\main.c
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-5]: [c_cpp_properties]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching 'c_cpp_properties.json' from 'C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3'
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-5]: [clang_complete_file]:[get]: for file C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src\main.c
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-5]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[tools.py]:[search]:[Thread-5]: searching '.clang_complete' from 'C:\Users\username\repositories\workspace\ledbarPretty_v1.3\Src' to 'C:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3'
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: view is 25
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: translation unit does not exist. Creating.
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-5]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c', '-std=c11', '-IC:\\Program Files\\LLVM\\lib\\clang\\8.0.0\\include', '-I\\usr\\include', '-IC:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3\\src', '-I\\usr\\lib\\clang\\8.0.0\\include', '-IC:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3\\Src', '-IC:\\Users\\username\\repositories\\workspace\\ledbarPretty_v1.3']
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-5]: compilation started for view id: 25
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-5]: compilation done in 0.015626907348632812 seconds
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: reparsing translation_unit for view 25
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-5]: reparsed in 0.03128814697265625 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-5]: generating error regions for view 25
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-5]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-5]: showing error regions: [(6724, 6741), (7704, 7725), (6750, 6766), (6970, 6987), (6773, 6790), (6798, 6815), (6823, 6840), (6848, 6865), (6880, 6897), (6912, 6929), (8613, 8618), (6945, 6962), (6320, 6322), (6997, 7015), (7024, 7042), (7830, 7850), (7830, 7850), (7830, 7850), (7753, 7774), (7655, 7676)]
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-5]: updated config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x000002044F443358>
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-6]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-6]: view file_name is None

```

**Comment by morcillo** [comment]
OK. I just got it working. The problem is that it just didn't matter if I added the include paths to the project file (.sublime-project) because it wasn't reading them. I then tried to open the EasyClangComxplete configuration  found in the preferences tab in sublime text and then ovewrote the common_flags configuration for the user. Then it started finding the files correctly and the autocomplete started working. 

The issue now is that:

1 - I think that modifying the project file should be enough and I shouldn't modify the configurations for ECC ... I've seen maaaaany posts were it works for other people, so there must be something wrong on my end;

2 - Autocomplete for a struct works, but it gives me many options and jumps to an option about 20 lines below the first ones, and the first ones are the actual members of the struct ... maybe another wrong configuration in my part;

3 - It gives me a warning that snprintf is implicitly declared, but I already added the correct include file and after some searching it says that it's only defined for c99, and when I went to the configurations it apparently was configured for c11, so I changed it to c99 but it didn't work, This one isn't actually a problem, it's just bothering me because I don't want to see the warning sign on the left side.

**Comment by niosus** [comment]
1. It is a little bit cumbersome sometimes to figure out why sometimes project files don't work. It is important to make sure the project is opened in sublime text, so that the files are assiociated to it. This is not always the case, then the files cannot read the settings from there.
2. By default I don't disable the default sublime text completions. You can always set `hide_default_completions` to `true`.
3. here I can't help you much I guess without seeing the code...

**Comment by morcillo** [comment]
@niosus Thank you very much for your help. 

- About the project file not working .. not a problem. I can live with  eidting the other file. 
- About the hide_default_completion .. yeah before I got it working I started changing everything I could to see if anything changed and apparently I forgot to reverse that and other configurations
- About the snprintf .. absolutely no problem. 

Please let me consider this issue as closed by stating how much I am enjoying your plugin. It is absolutely great and very helpful.

**Comment by niosus** [comment]
Alright, then I will close this issue :) Happy that you like it, means really a lot to me! If you do like it, spread the news to others ;)

**Comment by acourt** [comment]
I have the same issue, but after reading this conversation I am not sure what the prescribed solution is?

**Comment by morcillo** [comment]
@acourt First try putting the ECC configuration into ECC's configurations and not the project's configurations. 

For some reason it doesn't work when I put it in the project configurations it doesn't work. Don't forget to turn on verbose to see if you get any output from ECC. 

Go to preferences > Package Settings > EasyClangComplete > Settings

on the right side try putting something like this:

```
{
	"common_flags" :[
	        "-I/usr/include",
            "-I$project_base_path/src",
            "-I$project_base_path/Inc",
            "-I$project_base_path/Drivers/STM32F4xx_HAL_Driver/Inc",
            "-I$project_base_path/Drivers/CMSIS/Device/ST/STM32F4xx/Include",
            "-I$project_base_path/Middlewares/Third_Party/FatFs/src",
            "-DSTM32F411xE",
            "-U_WIN32",
            "-I/usr/lib/clang/$clang_version/include"
	],
	"lang_flags": {
    	"C": ["-std=c99"],
    	"CPP": ["-std=c++99"],
    	"OBJECTIVE_C": ["-std=c11"],
    	"OBJECTIVE_CPP": ["-std=c++11"],
  	},
}
```
Also ... 
"show_errors": true,
"verbose" : true,


After that open the console and see what ECC tells you.

**Comment by acourt** [comment]
When I put the paths in the package settings it works. However, this isn't the best solution since not all projects have the same folder structure. Should we make a separate issue for why the ECC isn't parsing the project file?

**Comment by acourt** [comment]
Putting paths in a `.clang_complete` file works well though.
