### ISSUE TITLE
ECC failing on start up

### ISSUE THREAD

**Issue by smfelsher** [niosus/EasyClangComplete#588]
# System info: #
- Sublime Text version: `3.2.1, Build 3207`
- Which system are you on: `Linux Mint 18.3`
- Clang version: `7.1.0`

# What happens:  #
The latest ECC update caused Sublime to "freeze" after it was installed. Forced Sublime to quit and restarted Sublime. Now, ECC is not displaying type information, etc. See ECC errors in log.

<details>
<summary>Log that illustrates the issue: </summary>
  
```
startup, version: 3207 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/steve/.config/sublime-text-3/Packages
state path: /home/steve/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/steve/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.721476
loading dictionary Packages/Language - English/en_US.dic
startup time: 0.905545
git: tracking working dir /home/steve/sandboxes/vipro-bootloaders
first paint time: 0.919531
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.plugin
reloading plugin ANSIescape.ansi
reloading plugin Boxy Theme.BT
reloading plugin Boxy Theme.Icons
reloading plugin Clang Format.clang_format
reloading plugin CMake.AutoComplete
reloading plugin CMakeFormat.cmake_format
reloading plugin DoxyDoxygen (evolution).Doxy
------==== DoxyDoxygen (evolution) plugins loaded ====------
0 sub-modules to reload
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeGit.SublimeGit
reloading plugin SublimeGoogle.SublimeGoogle
reloading plugin SublimeManpage.SublimeManpage
reloading plugin TerminalView.exec
reloading plugin TerminalView.gateone_terminal_emulator
reloading plugin TerminalView.linux_pty
reloading plugin TerminalView.pyte_terminal_emulator
reloading plugin TerminalView.sublime_terminal_buffer
reloading plugin TerminalView.sublime_view_cache
reloading plugin TerminalView.TerminalView
reloading plugin TerminalView.utils
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin TodoReview.TodoReview
plugins loaded
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 27. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: flags_sources              <-- '[{'file': 'compile_commands.json', 'search_in': '$project_base_path/build-tests'}]'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[MainThread]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[MainThread]: Populated '$project_base_path/build-tests' to '['/home/steve/sandboxes/vipro-bootloaders/build-tests']'
[ECC:CRITICAL]:[settings_storage.py]:[__update_ignore_list]:[MainThread]:  Cannot update paths of ignore list.
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[MainThread]: settings initialized for view: 27
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[MainThread]: on_activated_async view id 27
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-4]: generate new config for path: 27
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-4]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-4]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Platform: Linux, ('64bit', '')
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Python version: 3.3.6
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: User provided libclang_path: '<some_path_here>'
[ECC:DEBUG]:[utils.py]:[get_folder_and_name]:[Thread-4]: User provided wrong libclang path: '<some_path_here>'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Searching for: 'libclang-7.1.so'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Generating search folder
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Libclang search output = 'libclang-7.1.so'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-4]: real output: libclang-7.1.so
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Checking path: ./libclang-7.1.so
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Clang could not find './libclang-7.1.so'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Searching for: 'libclang.so'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Generating search folder
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Libclang search output = 'libclang.so'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-4]: real output: libclang.so
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Checking path: ./libclang.so
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Clang could not find './libclang.so'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Searching for: 'libclang-7.1.so.1'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Generating search folder
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-6]: on_activated_async view id 27
[ECC:DEBUG]:[singleton_thread_pool.py]:[new_job]:[Dummy-6]: Cannot cancel job: 'job: 'update''
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Libclang search output = 'libclang-7.1.so.1'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-4]: real output: libclang-7.1.so.1
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Checking path: ./libclang-7.1.so.1
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Clang could not find './libclang-7.1.so.1'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Searching for: 'libclang.so.1'
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Generating search folder
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Libclang search output = '/usr/lib/llvm-7/bin/../lib/libclang.so.1'
[ECC:DEBUG]:[utils.py]:[dir_from_output]:[Thread-4]: real output: /usr/lib/llvm-7/bin/../lib/libclang.so.1
[ECC:DEBUG]:[utils.py]:[find_libclang]:[Thread-4]: Checking path: /usr/lib/llvm-7/lib/libclang.so.1
[ECC:INFO]:[utils.py]:[find_libclang]:[Thread-4]: Found libclang library file: '/usr/lib/llvm-7/lib/libclang.so.1'
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-4]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-4]: Tokenizing: ['-x', 'c++']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-4]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-4]: Source
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-4]: view became invalid while loading config: 'list' object has no attribute 'startswith'
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-4]: traceback: Traceback (most recent call last):
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 486, in load_for_view
    config = ViewConfig(view, settings)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 70, in __init__
    view, settings)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 190, in __generate_essentials
    source_flags = ViewConfig.__load_source_flags(view, settings, prefixes)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 293, in __load_source_flags
    from_folder=path.normpath(search_folder))
  File "./python3.3/posixpath.py", line 356, in normpath
AttributeError: 'list' object has no attribute 'startswith'

[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-4]: updated config: None
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-4]: generate new config for path: 27
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-4]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-4]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-4]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-4]: Tokenizing: ['-x', 'c++']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-4]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-4]: Source
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-4]: view became invalid while loading config: 'list' object has no attribute 'startswith'
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-4]: traceback: Traceback (most recent call last):
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 486, in load_for_view
    config = ViewConfig(view, settings)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 70, in __init__
    view, settings)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 190, in __generate_essentials
    source_flags = ViewConfig.__load_source_flags(view, settings, prefixes)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 293, in __load_source_flags
    from_folder=path.normpath(search_folder))
  File "./python3.3/posixpath.py", line 356, in normpath
AttributeError: 'list' object has no attribute 'startswith'

[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-4]: updated config: None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-6]: view file_name is None
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-6]: on_activated_async view id 27
[ECC:DEBUG]:[view_config.py]:[load_for_view]:[Thread-4]: generate new config for path: 27
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-4]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-4]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-4]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-4]: Tokenizing: ['-x', 'c++']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-4]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-4]: Source
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-4]: view became invalid while loading config: 'list' object has no attribute 'startswith'
[ECC:ERROR]:[view_config.py]:[load_for_view]:[Thread-4]: traceback: Traceback (most recent call last):
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 486, in load_for_view
    config = ViewConfig(view, settings)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 70, in __init__
    view, settings)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 190, in __generate_essentials
    source_flags = ViewConfig.__load_source_flags(view, settings, prefixes)
  File "/home/steve/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config.py", line 293, in __load_source_flags
    from_folder=path.normpath(search_folder))
  File "./python3.3/posixpath.py", line 356, in normpath
AttributeError: 'list' object has no attribute 'startswith'

[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-4]: updated config: None
Package Control: Skipping automatic upgrade, last run at 2019-04-14 09:56:12, next run at 2019-04-14 10:56:12 or after
[ECC:DEBUG]:[view_config.py]:[trigger_info]:[Thread-4]: Config is not ready yet. No info tooltip shown.
```

</details>

**Comment by niosus** [comment]
Sorry for the inconvenience. I think I know what can be happening. But in case I'm wrong, can you show me your settings and tell me what you are doing exactly? I will try to fix it today night.

**Comment by niosus** [comment]
More specifically, do you have a `"search_in"` statement in your settings that holds a wildcard that you expect to be expanded?

**Comment by smfelsher** [comment]
Yes, I have a "search_in" statement in my settings.

"ecc_flags_sources":
[
   {
      "file": "compile_commands.json",
      "search_in": "$project_base_path/build-tests",
   },
],
--
Steve Felsher, Jr.

**Comment by niosus** [comment]
Should be fixed in the release rolling out now.

**Comment by smfelsher** [comment]
Thank you very much!
