### ISSUE TITLE
Error upon c++ completion processing

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#6]
When introducing error in c++ and autocompleting using clang binary an error occurs:
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "C:\Users\%username%\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\clang_bin_complete.py", line 205, in complete
    complete_results)
  File "C:\Users\%username%\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\clang_bin_complete.py", line 270, in _process_completions
    comp_dict = pos_search.groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

Moving it here from issue #4

**Comment by niosus** [comment]
I have fixed this bug and will close the issue. @simonhaenisch feel free to reopen it if you still experience this bug.
