### ISSUE TITLE
libclang.dll found but cannot initialize completer with libclang

### ISSUE THREAD

**Issue by Gpinchon** [niosus/EasyClangComplete#617]
# System info: #
- Sublime Text version: 3.2.1
- Which system are you on: Windows 10
- Clang version: 8.0.0

# What happens:  #
I installed Easy Clang Complete, pointed it to clang++.exe in mingw64 bin folder, gave it the path to libclang.dll, it finds everything but always fails with a WinError126 and show_type_info error dialog pops up...

<details>
<summary>Log : </summary>
  
```
ERROR:concurrent.futures:exception calling callback for <Future at 0x159f60a9d68 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\Users\[USER]\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 436, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Using user-provided libclang: 'C:\msys64\mingw64\bin\libclang.dll'
[ECC:ERROR  ]: error: [WinError 126] Le module spécifié est introuvable. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Using user-provided libclang: 'C:\msys64\mingw64\bin\libclang.dll'
[ECC:ERROR  ]: error: [WinError 126] Le module spécifié est introuvable. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Using user-provided libclang: 'C:\msys64\mingw64\bin\libclang.dll'
[ECC:ERROR  ]: error: [WinError 126] Le module spécifié est introuvable. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
```

</details>

**Comment by Gpinchon** [comment]
Okay, after setting libclang_path to "C:/msys64/mingw64/bin/" it seems to stop complaining about libclang.dll but still fails.

```
[ECC:INFO   ]: settings changed and reloaded
[ECC:INFO   ]: Getting version from command: `C:/msys64/mingw64/bin/clang++ -v`
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

ERROR:concurrent.futures:exception calling callback for <Future at 0x159f6741b70 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\Users\[USER]\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 436, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
```

**Comment by Gpinchon** [comment]
With libclang_path set to "<SOMEPATH>" it finds libclang.dll by itself but still fails.
```
[ECC:INFO   ]: Getting version from command: `C:/msys64/mingw64/bin/clang++.exe -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Found libclang library file: 'C:\msys64\mingw64\bin\libclang.dll'
[ECC:ERROR  ]: error: [WinError 126] Le module spécifié est introuvable. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
```

**Comment by Gpinchon** [comment]
I found a trick in order to "fix" this issue, I wrote a small bat in order to run Sublime Text with MINGW64's environment, and now everything is working fine.
```
c:\msys64\usr\bin\env MSYSTEM=MINGW64 c:\msys64\usr\bin\bash -l -c "'c:\Program Files\Sublime Text 3\sublime_text.exe' &"
```

**Comment by mheinzler** [comment]
I'm doing the same with MSYS2 but using the [Environment Settings](https://packagecontrol.io/packages/Environment%20Settings) package with settings similar to:
```json
{
	"env": {
		"Windows": {
			"PATH": "C:\\msys2\\mingw64\\bin;C:\\msys2\\usr\\bin;%PATH%",
			"MSYSTEM": "MINGW64",
			"CHERE_INVOKING": "enabled_from_arguments"
		}
	}
}
```

This has been working very well for me.

**Comment by niosus** [comment]
Sorry for radio silence guys. Cannot find the time to properly look into this. @mheinzler would you be open to add that to the docs? Or just formulate why you have to do what you are doing and write up exactly what needs to be done? Then I would eventually put it into the documentation.

**Comment by mheinzler** [comment]
Sure, no problem. I will create a PR.
