### ISSUE TITLE
TypeError: expected string or buffer in glob on an unsaved buffer

### ISSUE THREAD

**Issue by dreamcat4** [niosus/EasyClangComplete#620]
# System info: #
- Sublime Text version: `3.2.1 build 3207`
- Which system are you on: `ubuntu 19.04`
- Clang version: `8.0.0-3`

# What happens:  #

`TypeError: expected string or buffer`

Upon startup I can see there is an exception being thrown in your code. Not certain of the implications of this error to the running plugin. As to how serious it is. But we can see in the log that the same error output repeats itself several times. Maybe like it's failed to load and is trying again.

It appears that the failing code in question is trying to get some system paths. By executing the command `clang++ -v`. And then parsing the textual output from that. To convert it into some array of paths or whatever. IDK.

However when I execute this same stated command in a local terminal window. Then i get the following output:

<details>

```sh
$ clang++ -v
clang version 8.0.0-3 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
</details>

Which would seem to indicate some valid output. So in short: not sure whats the problem here. If the plugin got that returned in the stdout. Then it should have worked eh allright?

<details>
<summary>Log that illustrates the issue: </summary>

```
[SublimePackageSync] Syncing all packages.
[SublimePackageSync] Done!
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-17]: no settings for view 86. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-17]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-17]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/src' to '/src'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '/usr/lib/clang/$clang_version/include' to '['/usr/lib/llvm-8/lib/clang/8.0.0/include']'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$file_path' to '['/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/User']'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '~/some_folder/*' to '/home/id/some_folder/*'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/some/project/path/*' to '/some/project/path/*'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-17]: settings initialized for view: 86
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-17]: ECC does nothing for language syntax: 'Sublime Text Settings'
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-17]: ECC does nothing for language syntax: 'Sublime Text Settings'
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-17]: no settings for view 122. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-17]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-17]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/src' to '/home/id/.config/sublime-text-3/src'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '/usr/lib/clang/$clang_version/include' to '['/usr/lib/llvm-8/lib/clang/8.0.0/include']'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 275, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 136, in update_from_view
    self.__populate_common_flags()
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 278, in __populate_common_flags
    current_folder=self.project_folder)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/flag.py", line 166, in build_with_expansion
    current_folder=current_folder):
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 325, in expand_all
    all_paths = glob(expanded_path)
  File "./python3.3/glob.py", line 18, in glob
  File "./python3.3/glob.py", line 29, in iglob
  File "./python3.3/glob.py", line 90, in has_magic
TypeError: expected string or buffer
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-17]: no settings for view 119. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-17]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-17]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/src' to '/home/id/.config/sublime-text-3/src'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '/usr/lib/clang/$clang_version/include' to '['/usr/lib/llvm-8/lib/clang/8.0.0/include']'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 275, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 136, in update_from_view
    self.__populate_common_flags()
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 278, in __populate_common_flags
    current_folder=self.project_folder)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/flag.py", line 166, in build_with_expansion
    current_folder=current_folder):
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 325, in expand_all
    all_paths = glob(expanded_path)
  File "./python3.3/glob.py", line 18, in glob
  File "./python3.3/glob.py", line 29, in iglob
  File "./python3.3/glob.py", line 90, in has_magic
TypeError: expected string or buffer
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-17]: no settings for view 118. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-17]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-17]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/src' to '/home/id/.config/sublime-text-3/src'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '/usr/lib/clang/$clang_version/include' to '['/usr/lib/llvm-8/lib/clang/8.0.0/include']'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 275, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 136, in update_from_view
    self.__populate_common_flags()
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 278, in __populate_common_flags
    current_folder=self.project_folder)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/flag.py", line 166, in build_with_expansion
    current_folder=current_folder):
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 325, in expand_all
    all_paths = glob(expanded_path)
  File "./python3.3/glob.py", line 18, in glob
  File "./python3.3/glob.py", line 29, in iglob
  File "./python3.3/glob.py", line 90, in has_magic
TypeError: expected string or buffer
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-17]: no settings for view 117. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-17]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-17]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/src' to '/home/id/.config/sublime-text-3/src'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '/usr/lib/clang/$clang_version/include' to '['/usr/lib/llvm-8/lib/clang/8.0.0/include']'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 275, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 136, in update_from_view
    self.__populate_common_flags()
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 278, in __populate_common_flags
    current_folder=self.project_folder)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/flag.py", line 166, in build_with_expansion
    current_folder=current_folder):
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 325, in expand_all
    all_paths = glob(expanded_path)
  File "./python3.3/glob.py", line 18, in glob
  File "./python3.3/glob.py", line 29, in iglob
  File "./python3.3/glob.py", line 90, in has_magic
TypeError: expected string or buffer
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-17]: no settings for view 116. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-17]: Settings sucessfully read...
[ECC:INFO]:[tools.py]:[get_clang_version_str]:[Dummy-17]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-17]: Populating common_flags with current variables.
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '$project_path/src' to '/home/id/.config/sublime-text-3/src'
[ECC:DEBUG]:[tools.py]:[expand_all]:[Dummy-17]: Populated '/usr/lib/clang/$clang_version/include' to '['/usr/lib/llvm-8/lib/clang/8.0.0/include']'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 275, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 136, in update_from_view
    self.__populate_common_flags()
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/settings/settings_storage.py", line 278, in __populate_common_flags
    current_folder=self.project_folder)
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/flag.py", line 166, in build_with_expansion
    current_folder=current_folder):
  File "/home/id/Mega/dotfiles/ubuntu/.config/sublime-text-3/Packages/EasyClangComplete/plugin/tools.py", line 325, in expand_all
    all_paths = glob(expanded_path)
  File "./python3.3/glob.py", line 18, in glob
  File "./python3.3/glob.py", line 29, in iglob
  File "./python3.3/glob.py", line 90, in has_magic
TypeError: expected string or buffer
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
[ECC:DEBUG]:[tools.py]:[is_valid_view]:[Dummy-17]: view file_name is None
Package Control: Skipping automatic upgrade, last run at 2019-07-22 17:36:44, next run at 2019-07-22 18:36:44 or after
```

</details>

However if there are any other specific local tests you would like me to run then please let me know. Your plugin will remain disabled in the meantimes.

**Comment by niosus** [comment]
This is new to me. Thanks for reporting! I will try to reproduce this this week I hope.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niosus** [comment]
Looking a bit more into this, if you have default settings, it seems that the issue is somehow with parsing the flag: `"-I$file_path"`. I don't yet understand what can be wrong with this though.

**Comment by niosus** [comment]
Please check the PR. You should stop seeing the error.

**Comment by dreamcat4** [comment]
Thanks... yes I do have unsaved files / buffers open quite often. So maybe it's something related to that.

**Comment by niosus** [comment]
The PR above should remove the error, but you still probably won't get the completions on an unsaved buffer.

**Comment by niosus** [comment]
The PR above should have solved this. Please reopen if needed.
