### ISSUE TITLE
Clang 9.0 not supported

### ISSUE THREAD

**Issue by sprainbrains** [niosus/EasyClangComplete#630]
# System info: #
- Sublime Text version: 3.2.1, build 3207
- Which system are you on: Windows 10 build 1903
- Clang version: 9.0.0

# What happens:  #
After update i got error with following message:

> use_libclang" is false
> "show_type_info" is true.
> 
> Unfortunately, there is no way to show type info
> if you are not using libclang.
> 
> Please use libclang or set "show_type_info" to false.
> 
> If you *are* using libclang and still see this, open an issue.

But in my local setting "use_libclang" = true.

<details>
<summary>Log that illustrates the issue: </summary>
  
```
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

ERROR:concurrent.futures:exception calling callback for <Future at 0x22ed547eda0 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\Users\Nikolai\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 436, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:ERROR  ]: cmake has finished, but no compilation database.
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:ERROR  ]: cmake has finished, but no compilation database.

```

</details>

**Comment by niosus** [comment]
Something seems to be wrong with finding libclang for clang version 9.0.0. I have created a PR to fix that. Could you please try that?

**Comment by sprainbrains** [comment]
> Something seems to be wrong with finding libclang for clang version 9.0.0. I have created a PR to fix that. Could you please try that?

It's helped. Thanks. Now working fine)

**Comment by detly** [comment]
I am also experiencing this problem:

```text
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-5]: init completer based on libclang
[ECC:CRITICAL]:[lib_complete.py]:[__init__]:[Thread-5]:  No cindex module for clang version: 9.0.0
[ECC:ERROR]:[view_config.py]:[__init_completer]:[Thread-5]: cannot initialize completer with libclang.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-5]: falling back to using clang in a subprocess.
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-5]: init completer based on clang from cmd

...

[ECC:DEBUG]:[view_config.py]:[get_from_cache]:[Thread-5]: config: <EasyClangComplete.plugin.view_config.ViewConfig object at 0x7fc06fa81090>
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.
```

I'll see if the PR helps and let you know.

**Comment by detly** [comment]
Yep, it works!

**Comment by niosus** [comment]
@detly thanks a lot. I will merge it today, I guess.
