### ISSUE TITLE
cannot initialize completer with libclang

### ISSUE THREAD

**Issue by E-Rockalanche** [niosus/EasyClangComplete#643]
# System info: #
- Sublime Text version: `3.0`
- Which system are you on: `Windows 10`
- Clang version: `9.0.0`

# What happens:  #
The libclang.dll is found, but initialization fails.

<details>
<summary>Log that illustrates the issue: </summary>
  
```
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Eric/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Eric/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Eric/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.140997
startup time: 0.202997
first paint time: 0.202997
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin CoolFormat.Coolformat
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin GMLX.gmlx
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Eric\AppData\Roaming\Sublime Text 3\Packages\GMLX\gmlx.py", line 192, in <module>
    for arg in sys.argv[1:]:
AttributeError: 'module' object has no attribute 'argv'
reloading plugin SublimeGDB.resultparser
reloading plugin SublimeGDB.sublimegdb
plugins loaded
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Found libclang library file: 'C:\Program Files (x86)\LLVM\bin\libclang.dll'
[ECC:ERROR  ]: error: [WinError 193] %1 is not a valid Win32 application. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
error: 
EasyClangComplete:
"use_libclang" is false
"show_type_info" is true.

Unfortunately, there is no way to show type info
if you are not using libclang.

Please use libclang or set "show_type_info" to false.

If you *are* using libclang and still see this, open an issue.

ERROR:concurrent.futures:exception calling callback for <Future at 0x25668716c50 state=finished returned NoneType>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "C:\Users\Eric\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\EasyClangComplete.py", line 442, in info_finished
    (tooltip_request, current_popup) = future.result()
TypeError: 'NoneType' object is not iterable
[ECC:INFO   ]: init completer based on libclang
Package Control: Skipping automatic upgrade, last run at 2019-10-26 12:12:44, next run at 2019-10-26 13:12:44 or after
[ECC:INFO   ]: Found libclang library file: 'C:\Program Files (x86)\LLVM\bin\libclang.dll'
[ECC:ERROR  ]: error: [WinError 193] %1 is not a valid Win32 application. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
```

</details>

**Comment by E-Rockalanche** [comment]
I'm using the 32 bit versions of clang and python3.8

**Comment by niosus** [comment]
Please provide a *verbose* log. Otherwise, there is not much for me to work with.
