### ISSUE TITLE
Can't work in Cpp files

### ISSUE THREAD

**Issue by jingyuexing** [niosus/EasyClangComplete#657]
# System info: #
- Sublime Text version: `3211`
- Which system are you on: `windows`
- Clang version: `9.0.0`

# What happens:  #
can't work in CPP files,just C files

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
top level value must be an array
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
top level value must be an array
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
top level value must be an array
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
top level value must be an array
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
indexing [job 24]: no files were indexed out of the 1 queued, abandoning crawl
<zipfile.ZipFile object at 0x000001CF6C143278>
<zipfile.ZipFile object at 0x000001CF6C1435F8>
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
[ECC:INFO   ]: init completer based on libclang
[ECC:CRITICAL]:  No cindex module for clang version: 9.0.0
[ECC:ERROR  ]: cannot initialize completer with libclang.
[ECC:INFO   ]: falling back to using clang in a subprocess.
[ECC:INFO   ]: init completer based on clang from cmd
```

</details>

**Comment by jingyuexing** [comment]
<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "E:\Programming\sublime_text_3211\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable
<zipfile.ZipFile object at 0x00000192BEDFC6A0>
<zipfile.ZipFile object at 0x00000192BEDFC710>
<zipfile.ZipFile object at 0x00000192BF007F60>
<zipfile.ZipFile object at 0x00000192BF0079E8>
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "E:\Programming\sublime_text_3211\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable
<zipfile.ZipFile object at 0x00000192BEDF46D8>
<zipfile.ZipFile object at 0x00000192BEDF4240>
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "E:\Programming\sublime_text_3211\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable
top level value must be an array
<zipfile.ZipFile object at 0x00000192BF0309E8>
<zipfile.ZipFile object at 0x00000192BF030A58>
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "E:\Programming\sublime_text_3211\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable

```

</details>

**Comment by niosus** [comment]
Could you please follow the instructions in the issue template and provide a verbose log? Your log is not verbose and I need more information to be able to help.

**Comment by jingyuexing** [comment]
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "E:\Programming\sublime_text_3211\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable
<zipfile.ZipFile object at 0x0000025160D9FA58>
<zipfile.ZipFile object at 0x0000025160D9FC18>
[ECC:INFO   ]: Getting version from command: `clang++ -v`
Traceback (most recent call last):
  File "E:\Programming\sublime_text_3211\sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\EasyClangComplete.py", line 274, in on_activated_async
    settings = EasyClangComplete.settings_manager.settings_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 55, in settings_for_view
    self.__init_for_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_manager.py", line 103, in __init_for_view
    self.__settings_dict[view_id].update_from_view(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 128, in update_from_view
    self.__update_wildcard_values(view)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\settings\settings_storage.py", line 327, in __update_wildcard_values
    version_str = Tools.get_clang_version_str(self.clang_binary)
  File "E:\Programming\sublime_text_3211\Data\Packages\EasyClangComplete\plugin\tools.py", line 733, in get_clang_version_str
    if "Apple" in output_text:
TypeError: argument of type 'NoneType' is not iterable
```
</details>

**Comment by niosus** [comment]
That is still not a verbose log. Please set `verbose` setting to `true` and try again.

**Comment by jingyuexing** [comment]
thanks!

> That is still not a verbose log. Please set `verbose` setting to `true` and try again.

**Comment by jingyuexing** [comment]
when i open the cpp files,show me log like this
<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-11]: ECC does nothing for language syntax: 'Rcpp'
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-11]: ECC does nothing for language syntax: 'Rcpp'
[ECC:DEBUG]:[tools.py]:[get_view_lang]:[Dummy-11]: ECC does nothing for language syntax: 'Rcpp'
```

</details>

### ECC does nothing for language syntax: 'Rcpp'

**Comment by niosus** [comment]
Sorry for the delay. It seems you are using a different language syntax. You can add it to the valid language syntaxes. For that please update a setting of the plugin: 
```json
  // A dictionary that defines a mapping from language to an array of valid
  // syntaxes for it. The values here are good defaults, but feel free to
  // customize the list to your liking. When modifying this setting make sure
  // that all 4 languages have values.
  "valid_lang_syntaxes": {
    "C":              ["C", "C Improved", "C99", "Rcpp"],
    "CPP":            ["C++", "C++11"],
    "OBJECTIVE_C":    ["Objective-C"],
    "OBJECTIVE_CPP":  ["Objective-C++"]
  }
```

I will close this issue. Feel free to reopen it if it doesn't solve your problem.
