### ISSUE TITLE
Permission error on multi-user system

### ISSUE THREAD

**Issue by Andreasdahlberg** [niosus/EasyClangComplete#662]
# System info: #
- Sublime Text version: `3211`
- Which system are you on: `RHEL 7.7`
- Clang version: `8.0.0`

# What happens:  #
I am trying to use EasyClangComplete(great plugin!) on a multi-user system but as soon as a second user starts Sublime that user gets a permission error(see log below).

The cause seems to be that all users share _/tmp/_ and EasyClangComplete creates temporary files
with fixed names that are owned by the first user.

Our workaround was to append our username to the name of the created directory. But i'm not sure if this is a good solution that works on other platforms. 
```python
tempdir = path.join(tempfile.gettempdir(), "{}_{}".format(PKG_NAME, os.environ['USER'])
```

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:INFO   ]: Getting version from command: `clang++ -v`
[ECC:INFO   ]: init completer based on libclang
[ECC:INFO   ]: Found libclang library file: '/some/dumy/path/libclang.so'
exception calling callback for <Future at 0x7f26decc7790 state=finished raised PermissionError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 418, in config_updated
    log.debug("updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config_manager.py", line 90, in load_for_view
    config = ViewConfig(view, settings)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 65, in __init__
    view, settings)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 181, in __generate_essentials
    view, settings, completer.compiler_variant.need_lang_flags)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 380, in __get_default_flags
    filename=None)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/flags_sources/compiler_builtins.py", line 48, in __init__
    File(path.join(working_dir, filename))
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/file.py", line 39, in __init__
    open(self.__full_path, 'a+').close()
PermissionError: [Errno 13] Permission denied: '/tmp/EasyClangComplete/ECC_temp_file.cpp'
[ECC:INFO   ]: init completer based on libclang
exception calling callback for <Future at 0x7f26dcf0e550 state=finished raised PermissionError>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/EasyClangComplete.py", line 418, in config_updated
    log.debug("updated config: %s", future.result())
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config_manager.py", line 90, in load_for_view
    config = ViewConfig(view, settings)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 65, in __init__
    view, settings)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 181, in __generate_essentials
    view, settings, completer.compiler_variant.need_lang_flags)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 380, in __get_default_flags
    filename=None)
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/flags_sources/compiler_builtins.py", line 48, in __init__
    File(path.join(working_dir, filename))
  File "/home/<MY_USERNAME>/.config/sublime-text-3/Packages/EasyClangComplete/plugin/utils/file.py", line 39, in __init__
    open(self.__full_path, 'a+').close()
PermissionError: [Errno 13] Permission denied: '/tmp/EasyClangComplete/ECC_temp_file.cpp'
```

</details>

**Comment by niosus** [comment]
Thanks for submitting this! I never had this usecase but will think of something in the coming days.
