### ISSUE TITLE
Ability to make relative path for ecc_clang_binary

### ISSUE THREAD

**Issue by matreshkin** [niosus/EasyClangComplete#664]
# System info: #
- Sublime Text version: `3210`
- Which system are you on: `Ubuntu 18`
- Clang version: `7.0.0`

# What happens:  #
I am not able to point a relative path to `ecc_clang_binary` in my .sublime-project settings.
Meanwhile:
- Full path of  `ecc_clang_binary` works
- Relative path for `ecc_libclang_path` also works.
```
  "settings":
  {
    "ecc_flags_sources": [
        {
          "file": "compile_commands.json",
          "search_in": "${project_path}/../",
        },
      ],
    "ecc_use_libclang" : false,
    "ecc_show_type_info": false,
    "ecc_clang_binary": "${project_path}/../deps/clang/bin/clang",
    "ecc_libclang_path": "${project_path}/../deps/clang/lib/libclang.so",
  },
```

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:DEBUG]:[bin_complete.py]:[run_clang_command]:[Thread-18]: clang command: 
['${project_path}/../deps/clang/bin/clang', '-c', '-fsyntax-only', '-x', 'c++', '/tmp/EasyClangComplete/File.cc']
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-18]: Executable file not found executing: ['${project_path}/../deps/clang/bin/clang', '-c', '-fsyntax-only', '-x', 'c++', '/tmp/EasyClangComplete/File.cc']
[ECC:DEBUG]:[bin_complete.py]:[update]:[Thread-18]: rebuilding done in 0.005758523941040039 seconds
[ECC:ERROR]:[view_config_manager.py]:[load_for_view]:[Thread-18]: View became invalid while loading config: 'NoneType' object has no attribute 'splitlines'
[ECC:ERROR]:[view_config_manager.py]:[load_for_view]:[Thread-18]: Traceback: Traceback (most recent call last):
  File "/home/polikarpov/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config_manager.py", line 87, in load_for_view
    res = self.__cache[v_id].update_if_needed(view, settings)
  File "/home/polikarpov/.config/sublime-text-3/Packages/EasyClangComplete/plugin/view_config/view_config.py", line 95, in update_if_needed
    self.completer.update(view, settings)
  File "/home/polikarpov/.config/sublime-text-3/Packages/EasyClangComplete/plugin/completion/bin_complete.py", line 154, in update
    self.save_errors(output_text)
  File "/home/polikarpov/.config/sublime-text-3/Packages/EasyClangComplete/plugin/completion/base_complete.py", line 109, in save_errors
    self.latest_errors = self.compiler_variant.errors_from_output(output)
  File "/home/polikarpov/.config/sublime-text-3/Packages/EasyClangComplete/plugin/completion/compiler_variant.py", line 55, in errors_from_output
    for line in output.splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'`
```

</details>

**Comment by niosus** [comment]
Hmm, strange, I was sure I parse the paths. That might be the result of my last update. I will try to have a look tomorrow.

**Comment by niosus** [comment]
Will be available in v.6.2.4 in about an hour :wink:

**Comment by matreshkin** [comment]
Wow, so fast) Thanks a lot, it works now.

**Comment by niosus** [comment]
Glad it works :)
