### ISSUE TITLE
An erroneous warning

### ISSUE THREAD

**Issue by Feacur** [niosus/EasyClangComplete#744]
... I'm not sure if that's due to a compiler/analizer bug or something else

UPD: might be some clang issue: `LSP + clangd` show the same exact behaviour (https://github.com/clangd/clangd/issues/744)

# System info: #
- Sublime Text version: `Version 3.2.2, Build 3211`
- Which system are you on: `Windows 10 Home, 10.0.19042 Build 19042`
- Clang version: `10, x86_64-pc-windows-msvc, posix`

# What happens:  #
An erroneous warning `no new line at end of file` at an indented line near a forward declaration.

Minimal example 1:
```
#include <stdio.h>

	// reports `no new line at end of file`; forward declaration is mandatory
static void func(void);
int main(int argc, char const * argv[]) {
	(void)argc; (void)argv;
	func();
	return 0;
}

static void func(void) {
	printf("hello, world!\n");
}
```

Minimal example 2:

```
#include <stdio.h>

	static void func(void); // reports `no new line at end of file`; forward declaration is mandatory
int main(int argc, char const * argv[]) {
	(void)argc; (void)argv;
	func();
	return 0;
}

static void func(void) {
	printf("hello, world!\n");
}
```

Reference settings: https://github.com/Feacur/game_prototype/tree/master/__sublime_project

<details>
<summary>Log that illustrates the issue: </summary>
  
```
DPI mode: per-monitor v2
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Feacu/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Feacu/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Feacu/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.153752
startup time: 0.242752
first paint time: 0.245752
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-sublime_lib
reloading plugin 0_package_control_loader.10-wcwidth
reloading plugin 0_package_control_loader.40-pywinpty
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-pyte
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BuildX.ansi
reloading plugin BuildX.buildx
reloading plugin BuildX.test-color-scheme
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Feacu\AppData\Roaming\Sublime Text 3\Installed Packages\BuildX.sublime-package\test-color-scheme.py", line 5
    print(f"\x1b[0m\x1b[{code}m{name}\x1b[0m")
                                            ^
SyntaxError: invalid syntax
reloading plugin HexViewer.hex_checksum
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
reloading plugin ProjectManager.json_file
reloading plugin ProjectManager.project_manager
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin Terminus.main
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin User.plugins
plugins loaded
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[MainThread]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
Package Control: Skipping automatic upgrade, last run at 2021-04-13 12:56:55, next run at 2021-04-13 13:56:55 or after
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[MainThread]: view file_name is None
git: tracking working dir F:\Projects\game_prototype
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-5]: no settings for view 31. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: common_flags               <-- '['-std=c99', '-Werror', '-Weverything', '-Wno-switch-enum', '-Wno-float-equal', '-Wno-reserved-id-macro', '-Wno-nonportable-system-include-path', '-Wno-assign-enum', '-Wno-bad-function-cast', '-I..', '-I../third_party', '-DGAME_TARGET_DEBUG', '-D_CRT_SECURE_NO_WARNINGS', '-DWIN32_LEAN_AND_MEAN', '-DNOMINMAX', '-DUNICODE']'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: force_unix_includes        <-- 'True'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-5]: Settings sucessfully read...
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated 'C:/Program Files/LLVM/bin/clang.exe' to '['C:\\Program Files\\LLVM\\bin\\clang.exe']'
[ECC:INFO]:[clang_utils.py]:[get_clang_version_str]:[Dummy-5]: Getting version from command: `C:\Program Files\LLVM\bin\clang.exe -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-5]: Populating common_flags with current variables.
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated '..' to '['F:\\Projects\\game_prototype']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-5]: Populated '../third_party' to '['F:\\Projects\\game_prototype\\third_party']'
[ECC:CRITICAL]:[settings_storage.py]:[__populate_flags_source_paths]:[Dummy-5]:  Cannot update paths of flag sources.
[ECC:CRITICAL]:[settings_storage.py]:[update_from_view]:[Dummy-5]: Cannot expand ignore_list
[ECC:CRITICAL]:[settings_storage.py]:[update_from_view]:[Dummy-5]: Cannot expand ignore_flags
[ECC:CRITICAL]:[settings_storage.py]:[update_from_view]:[Dummy-5]: Cannot expand header_to_source_mapping
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-5]: settings initialized for view: 31
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-5]: on_activated_async view id 31
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[view_config_manager.py]:[load_for_view]:[Thread-9]: Generate new config for path: 31
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-9]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-9]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Platform: Windows, ('64bit', 'WindowsPE')
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Python version: 3.3.6
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: User provided libclang_path: '<some_path_here>'
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Searching for: 'libclang.dll'
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Generating search folder
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-5]: on_activated_async view id 31
[ECC:DEBUG]:[thread_pool.py]:[new_job]:[Dummy-5]: Cannot cancel job: 'job: 'Updating translation unit''
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-5]: on_activated_async view id 31
[ECC:DEBUG]:[thread_pool.py]:[new_job]:[Dummy-5]: Cannot cancel job: 'job: 'Updating translation unit''
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Dummy-5]: could not update config -> cancelled
[ECC:DEBUG]:[thread_pool.py]:[new_job]:[Dummy-5]: Canceled job: 'job: 'Updating translation unit''
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-5]: on_activated_async view id 31
[ECC:DEBUG]:[thread_pool.py]:[new_job]:[Dummy-5]: Cannot cancel job: 'job: 'Updating translation unit''
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Dummy-5]: could not update config -> cancelled
[ECC:DEBUG]:[thread_pool.py]:[new_job]:[Dummy-5]: Canceled job: 'job: 'Updating translation unit''
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Libclang search output = 'C:\Program Files\LLVM\bin\clang'
[ECC:DEBUG]:[clang_utils.py]:[dir_from_output]:[Thread-9]: Real output: C:\Program Files\LLVM\bin\clang
[ECC:DEBUG]:[clang_utils.py]:[dir_from_output]:[Thread-9]: Architecture: ('64bit', 'WindowsPE')
[ECC:DEBUG]:[clang_utils.py]:[dir_from_output]:[Thread-9]: Folder to search: C:\Program Files\LLVM\bin\clang\..
[ECC:DEBUG]:[clang_utils.py]:[find_libclang]:[Thread-9]: Checking path: C:\Program Files\LLVM\bin\libclang.dll
[ECC:INFO]:[clang_utils.py]:[find_libclang]:[Thread-9]: Found libclang library file: 'C:\Program Files\LLVM\bin\libclang.dll'
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-9]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-9]: Tokenizing: ['-x', 'c', '-std=c99']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Source
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Merge
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-9]: lang flags: [(-x c), (-std=c99)]
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Appending and filtering flags with ignore patterns: []
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: view is 31
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: translation unit does not exist. Creating.
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-9]: clang flags are: ['-c', '-fsyntax-only', '-x', 'c', '-std=c99', '-Werror', '-Weverything', '-Wno-switch-enum', '-Wno-float-equal', '-Wno-reserved-id-macro', '-Wno-nonportable-system-include-path', '-Wno-assign-enum', '-Wno-bad-function-cast', '-I', 'F:\\Projects\\game_prototype', '-I', 'F:\\Projects\\game_prototype\\third_party', '-DGAME_TARGET_DEBUG', '-D_CRT_SECURE_NO_WARNINGS', '-DWIN32_LEAN_AND_MEAN', '-DNOMINMAX', '-DUNICODE']
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-9]: compilation started for view id: 31
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-9]: compilation done in 0.057116031646728516 seconds
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: reparsing translation_unit for view 31
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: reparsed in 0.10130786895751953 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: Generating error regions for view 31
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-9]: Showing error regions: [(21, 27)]
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-9]: Showing warning regions: []
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-9]: updated config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x000001978C4CB358>
[ECC:DEBUG]:[view_config_manager.py]:[load_for_view]:[Thread-9]: Config exists for path: 31
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-9]: init completer based on libclang
[ECC:DEBUG]:[lib_complete.py]:[__init__]:[Thread-9]: using bundled cindex: EasyClangComplete.plugin.clang.cindex50
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-9]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-9]: Tokenizing: ['-x', 'c', '-std=c99']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Source
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Merge
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-9]: lang flags: [(-x c), (-std=c99)]
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-9]: Appending and filtering flags with ignore patterns: []
[ECC:DEBUG]:[view_config.py]:[needs_update]:[Thread-9]: view config needs no update.
[ECC:DEBUG]:[file.py]:[is_unchanged]:[Thread-9]: never seen file 'F:\Projects\game_prototype\prototype\test.c' before. Updating.
[ECC:DEBUG]:[view_config.py]:[update_if_needed]:[Thread-9]: config updates existing completer.
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: view is 31
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: reparsing translation_unit for view 31
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-9]: reparsed in 0.006021022796630859 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: Generating error regions for view 31
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: Removing old error regions
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-9]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-9]: Showing error regions: [(21, 27)]
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-9]: Showing warning regions: []
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-9]: updated config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x000001978C4CB358>
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-5]: view file_name is None
```

</details>

**Comment by niosus** [comment]
Just for completeness, did this problem just go away @Feacur?

**Comment by Feacur** [comment]
@niosus, no, no; but, as that's not a bug of ECC or LSP, I've filed a new issue at the `clangd` side, which is the primary source.

**Comment by niosus** [comment]
Got it, thanks.
