### ISSUE TITLE
Crash on drag-selection near an error

### ISSUE THREAD

**Issue by Feacur** [niosus/EasyClangComplete#745]
# System info: #
- Sublime Text version: `Version 3.2.2, Build 3211`
- Which system are you on: `Windows 10 Home, 10.0.19042 Build 19042`
- Clang version: `10, x86_64-pc-windows-msvc, posix`

# What happens:  #
Sublime Text crashes if you select text **too hard** with mouse at the error line with a popup. Just drag-select some text there a lot.

I used `SublimeLog` plugin to get the crash trace.

Minimal example: any, but #744 will do too

<details>
<summary>Log that illustrates the issue: </summary>
  
```
=> => => [13 Apr 2021, 13:41:39] Console logging activated (C:\Users\Feacu\.subl.log).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Feacu\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\utils\thread_pool.py", line 126, in __animate_progress
    self.__progress_status.show_as_ready()
  File "C:\Users\Feacu\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\utils\progress_status.py", line 49, in show_as_ready
    BaseProgressStatus.PROGRESS_MASK.format(progress=self.msg_ready))
  File "C:\Users\Feacu\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\utils\progress_status.py", line 36, in set_status
    view.set_status(BaseProgressStatus.MSG_TAG, message)
AttributeError: 'NoneType' object has no attribute 'set_status'
```

</details>

**Comment by niosus** [comment]
Ok, thanks for reporting. I will try to have a look as soon as I find the time.

**Comment by niosus** [comment]
Judging from the log it should be not too hard to fix.

**Comment by niosus** [comment]
@Feacur I added a PR, but I could not reproduce this. Granted I did try this on by Linux machine, but still. Just in case I was doing smth wrong, am I "selecting too hard" right? 

https://user-images.githubusercontent.com/1893598/115149346-eb034a80-a063-11eb-81bb-7cf6ac0e19d4.mp4

**Comment by Feacur** [comment]
Yes, exactly like that =)

The crash persist even with the PR, although now without the said trace. I'll test a bit more searching for the source[s] of it; without any additional leads, there is no much use to this issue anyway.

For me it looks like this:
![image](https://user-images.githubusercontent.com/1132582/115150552-8bac3700-a071-11eb-8674-4e19efe39373.png)
![image](https://user-images.githubusercontent.com/1132582/115150855-d7131500-a072-11eb-9ddf-993510732769.png)

**Comment by Feacur** [comment]
Ok, superficially traced the offender:
```
# /EasyClangComplete/EasyClangComplete.py
    def on_selection_modified_async(self, view):
        # ...

# /EasyClangComplete/plugin/error_vis/popup_error_vis.py
    def show_popup_if_needed(self, view, row):
        # ...

# /EasyClangComplete/plugin/error_vis/popups.py
    def show(self, view, location=-1, on_navigate=None):
        # ...
```
... without these popups [**spamming**, while user drag-selects stuff,] everything's going just fine. Also, I've noticed `info` popups take completely different paths to occur, unlike `warning` and `error` ones.

**Comment by niosus** [comment]
This is all really weird. With all the things you commented out you would not get the popups at all, right?

**Comment by Feacur** [comment]
Yeah: should I only disable `popup.show(view)` call in the `popup_error_vis.py`, everything comes stable. Obviously, without the said popups, which is a mild inconvenience; but `ECC: Show all errors` and gutter icons still function all right, so not everything's lost. Besides, keyboard controls aren't affected by the issue, so normally I wouldn't get the crash.

**Comment by niosus** [comment]
I see. This is really strange. I will probably also try to run this on Windows just to see if I am able to reproduce it there. The popups are most probably generated in different ways on linux and windows. Until then, it _is_ weird. On my machine, sublime text never crashes unless there is a legitimate bug in the plugin code, so it _might_ be related to your configuration.

**Comment by Feacur** [comment]
Sure, it might be. I did disable all the other plugins before taking the screenshots; but it still leaves the rest of my machine to interference the editor.

(also, ugh, sorry, I've accidentally misclicked the [close issue] button and got no prompt)

**Comment by niosus** [comment]
@Feacur I've tried reproducing this on my Windows machine and it just won't crash. Is your machine special in any way?

**Comment by Feacur** [comment]
Most likely it is, as any other PC
- there is a fair lot of dev tools, for sure
- some system settings and permissions may differ
- well, drivers/hardware/running services/whatnot

I can't pinpoint any other particular cause, unless I dig deeper the callstack into `mdpopups`, for instance.

Anyway, thank you for trying to reproduce it at your side and for your time.
