### ISSUE TITLE
It doesn't work on OS X El Captain.

### ISSUE THREAD

**Issue by david9991** [niosus/EasyClangComplete#86]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/EasyClangComplete.py", line 65, in plugin_loaded
    completer = lib_complete.Completer(settings.clang_binary)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/completion/lib_complete.py", line 58, in __init__
    super(Completer, self).__init__(clang_binary)
  File "/Users/David/Library/Application Support/Sublime Text 3/Packages/EasyClangComplete/plugin/completion/base_complete.py", line 76, in __init__
    self.version_str = tools.OSX_CLANG_VERSION_DICT[osx_version]
KeyError: '8.0'

**Comment by niosus** [comment]
Should be fixed in version 1.3.5. Will be live in half an hour or so.

**Comment by niosus** [comment]
I guess folks at TravisCI changed something in their OSX build sometimes the builds fail. I don't know the reason for this yet, but it has to work.

**Comment by randy3k** [comment]
Originally, when Sublime Text is opened on macOS, it should open an empty open. But the version of ST closes the window automatically (or never open such window) which breaks view related commands.

Unittesting [travis.sh](https://github.com/randy3k/UnitTesting/commit/b48eb0faa3dceb14e2430fde40e3cb9ef5ea180b) has been updated to force the setting `close_windows_when_empty` to false.

**Comment by niosus** [comment]
Great! Now everything is fine. Thanks @randy3k
